// Generated by scripts/characterisation/capture-fixtures.mjs on 2026-09-29 -- see fixtures.ts.
// Workspace A's administrator (4537) and, for the tenant list, the platform administrator (1000); two rows per list,
// credentials, e-mails, addresses, endpoints and people's names replaced.
/* eslint-disable */
export const LIVE_IDS = {"jobId":2833,"jobQueueId":7331,"taskId":1854,"promptId":1049,"pipelineId":"REF_CSV_CHECK_V1","bucket":"ui-review-s3"} as const;

export const LIVE: Record<string, unknown> = {
  "GET /notification.json/unreadCount": {
    "status": "SUCCESS",
    "message": "Unread count fetched.",
    "data": 4
  },
  "GET /notification.json/list": {
    "status": "SUCCESS",
    "message": "Notifications fetched.",
    "data": [
      {
        "notificationId": 3691,
        "type": "JOB_COMPLETED",
        "severity": "SUCCESS",
        "title": "Job completed",
        "message": "UI-REVIEW Ledger nightly (daily 02:00, 3 attempts) finished successfully.",
        "linkUrl": "/operations/jobs/2835/history",
        "read": false,
        "dateCreated": "2026-09-28T02:02:37.806393"
      },
      {
        "notificationId": 3690,
        "type": "JOB_COMPLETED",
        "severity": "SUCCESS",
        "title": "Job completed",
        "message": "UI-REVIEW Ledger nightly (daily 02:00, 3 attempts) finished successfully.",
        "linkUrl": "/operations/jobs/2835/history",
        "read": false,
        "dateCreated": "2026-09-27T02:00:10.367764"
      }
    ],
    "paging": {
      "totalRecord": 44,
      "pageSize": 20,
      "currentPage": 1
    }
  },
  "GET /sourceJob.json/listSourceJob": {
    "status": "SUCCESS",
    "message": "Fetch source jobs.",
    "data": [
      {
        "createdByName": "Casey Baseline",
        "updatedByName": "Casey Baseline",
        "createdBy": 4537,
        "jobId": 2833,
        "tenantId": 2924,
        "jobName": "Reference CSV check (e2e)",
        "taskDetail": {
          "taskDetailId": 1854,
          "taskName": "Reference: CSV check and summarise",
          "taskStatus": "Active",
          "pipelineId": "REF_CSV_CHECK_V1",
          "bucket": "etl-bucket",
          "sourceTaskType": {
            "sourceTaskTypeId": 11831,
            "serviceName": "service-1 reference worker",
            "description": "service-1 worker runtime reference pipeline (WORKER-CONTRACT.md)",
            "queueTopicPartition": "topic=etl.reference&partitions=[*]"
          }
        },
        "assignedUserId": 4537,
        "assignedUsername": "person@example.com",
        "jobStatus": "Active",
        "jobRunningStatus": "Completed",
        "lastJobRun": "2026-09-24T22:06:12.024422",
        "execution": "Manual",
        "priority": 5,
        "maxAttempts": 1,
        "retryBackoffSeconds": 60,
        "dateCreated": "2026-09-25T03:06:11.978+00:00",
        "completeJob": true,
        "failJob": true,
        "skipJob": true,
        "tabActive": true,
        "stalled": false
      },
      {
        "createdByName": "Casey Baseline",
        "updatedByName": "Casey Baseline",
        "createdBy": 4537,
        "jobId": 2834,
        "tenantId": 2924,
        "jobName": "UI-REVIEW Clean customers (manual, notify on completion)",
        "taskDetail": {
          "taskDetailId": 1855,
          "taskName": "UI-REVIEW Clean customers CSV check",
          "taskStatus": "Active",
          "homePageId": "UI-REVIEW Finance home",
          "pipelineId": "REF_CSV_CHECK_V1",
          "bucket": "etl-bucket",
          "sourceTaskType": {
            "sourceTaskTypeId": 11831,
            "serviceName": "service-1 reference worker",
            "description": "service-1 worker runtime reference pipeline (WORKER-CONTRACT.md)",
            "queueTopicPartition": "topic=etl.reference&partitions=[*]"
          }
        },
        "assignedUserId": 4537,
        "assignedUsername": "person@example.com",
        "jobStatus": "Active",
        "jobRunningStatus": "Completed",
        "lastJobRun": "2026-09-24T23:25:56.993645",
        "execution": "Manual",
        "priority": 5,
        "maxAttempts": 1,
        "retryBackoffSeconds": 60,
        "dateCreated": "2026-09-25T03:39:11.641+00:00",
        "completeJob": true,
        "failJob": true,
        "skipJob": true,
        "tabActive": true,
        "stalled": false
      }
    ]
  },
  "GET /sourceJob.json/fetchSourceJobDetailWithSourceJobId": {
    "status": "SUCCESS",
    "message": "SourceJob found with 2833.",
    "data": {
      "createdBy": 4537,
      "jobId": 2833,
      "tenantId": 2924,
      "jobName": "Reference CSV check (e2e)",
      "taskDetail": {
        "taskDetailId": 1854,
        "taskName": "Reference: CSV check and summarise",
        "taskStatus": "Active",
        "pipelineId": "REF_CSV_CHECK_V1",
        "taskPayload": "<csvCheck><inputKey>reference/input/sample.csv</inputKey><outputPrefix>reference/output</outputPrefix><maxRejectPercent>50</maxRejectPercent><requiredColumns>id,name</requiredColumns><numericColumns>amount</numericColumns><deleteInput>false</deleteInput><bucket>etl-bucket</bucket></csvCheck>",
        "bucket": "etl-bucket",
        "sourceTaskType": {
          "sourceTaskTypeId": 11831,
          "serviceName": "service-1 reference worker",
          "description": "service-1 worker runtime reference pipeline (WORKER-CONTRACT.md)",
          "queueTopicPartition": "topic=etl.reference&partitions=[*]"
        }
      },
      "assignedUserId": 4537,
      "assignedUsername": "person@example.com",
      "jobStatus": "Active",
      "jobRunningStatus": "Completed",
      "lastJobRun": "2026-09-24T22:06:12.024422",
      "execution": "Manual",
      "priority": 5,
      "maxAttempts": 1,
      "retryBackoffSeconds": 60,
      "dateCreated": "2026-09-25T03:06:11.978+00:00",
      "completeJob": true,
      "failJob": true,
      "skipJob": true,
      "tabActive": false,
      "stalled": false
    }
  },
  "GET /sourceJob.json/fetchSourceJobQueueListWithJobId": {
    "status": "SUCCESS",
    "message": "SourceJobQueue found with 2833.",
    "data": {
      "jobQueues": [
        {
          "jobQueueId": 7331,
          "startTime": "2026-09-24T22:06:12.024422",
          "endTime": "2026-09-24T22:06:52.424893",
          "jobStatus": "Completed",
          "jobId": 2833,
          "jobSend": true,
          "jobStatusMessage": "Checked 6 row(s) of reference/input/sample.csv: 4 accepted, 2 rejected. Summary: tenant-2924/reference/output/run-7331/summary.json",
          "runManual": true,
          "dateCreated": "2026-09-25T03:06:12.026+00:00"
        }
      ]
    }
  },
  "GET /sourceJob.json/findSourceJobAuditLog": {
    "status": "SUCCESS",
    "message": "SourceJob audit log found with 7331.",
    "data": {
      "auditLogs": [
        {
          "externalId": "aa195c65-0b98-470c-8f53-67e92e42e900",
          "jobQueueId": 7331,
          "logsDetail": "Job 2833 now in the queue.",
          "dateCreated": "2026-09-25T03:06:12.032Z",
          "correlationId": "01M3B8E555TQR2RT78AM141F4C",
          "status": "Active",
          "jobAuditLogId": 1104340584837081300
        },
        {
          "externalId": "cc6c6363-8f81-4afa-98c5-2d6f77794a3f",
          "jobQueueId": 7331,
          "logsDetail": "Job 2833 handed to the worker queue at offset 20.",
          "dateCreated": "2026-09-25T03:06:51.948Z",
          "correlationId": "01M3B8E555TQR2RT78AM141F4C",
          "status": "Active",
          "jobAuditLogId": 1784882784091327000
        }
      ],
      "sourceJob": {
        "createdBy": 4537,
        "jobId": 2833,
        "tenantId": 2924,
        "jobName": "Reference CSV check (e2e)",
        "taskDetail": {
          "taskDetailId": 1854,
          "taskName": "Reference: CSV check and summarise",
          "taskStatus": "Active",
          "pipelineId": "REF_CSV_CHECK_V1",
          "taskPayload": "<csvCheck><inputKey>reference/input/sample.csv</inputKey><outputPrefix>reference/output</outputPrefix><maxRejectPercent>50</maxRejectPercent><requiredColumns>id,name</requiredColumns><numericColumns>amount</numericColumns><deleteInput>false</deleteInput><bucket>etl-bucket</bucket></csvCheck>",
          "bucket": "etl-bucket",
          "sourceTaskType": {
            "sourceTaskTypeId": 11831,
            "serviceName": "service-1 reference worker",
            "description": "service-1 worker runtime reference pipeline (WORKER-CONTRACT.md)",
            "queueTopicPartition": "topic=etl.reference&partitions=[*]"
          }
        },
        "assignedUserId": 4537,
        "assignedUsername": "person@example.com",
        "jobStatus": "Active",
        "jobRunningStatus": "Completed",
        "lastJobRun": "2026-09-24T22:06:12.024422",
        "execution": "Manual",
        "priority": 5,
        "maxAttempts": 1,
        "retryBackoffSeconds": 60,
        "dateCreated": "2026-09-25T03:06:11.978+00:00",
        "completeJob": true,
        "failJob": true,
        "skipJob": true,
        "tabActive": false,
        "stalled": false
      },
      "sourceJobQueue": {
        "jobQueueId": 7331,
        "startTime": "2026-09-24T22:06:12.024422",
        "endTime": "2026-09-24T22:06:52.424893",
        "jobStatus": "Completed",
        "jobId": 2833,
        "jobSend": true,
        "jobStatusMessage": "Checked 6 row(s) of reference/input/sample.csv: 4 accepted, 2 rejected. Summary: tenant-2924/reference/output/run-7331/summary.json",
        "runManual": true,
        "dateCreated": "2026-09-25T03:06:12.026+00:00"
      }
    }
  },
  "GET /aiPrompt.json/runsForJob": {
    "status": "SUCCESS",
    "message": "0 AI step(s).",
    "data": []
  },
  "GET /aiAgent.json/fetchAllAgents": {
    "status": "SUCCESS",
    "message": "Data found.",
    "data": [
      {
        "aiAgentId": 1048,
        "agentName": "UI-REVIEW Summarise a CSV run in one paragraph",
        "description": "UI-REVIEW: v2 adds a tone variable.",
        "provider": "Ollama",
        "apiEndpoint": "redacted",
        "apiKeyConfigured": false,
        "model": "gemma3:1b",
        "targetFileTypes": "ui-review",
        "status": "Active",
        "jsonMode": false,
        "dateCreated": "2026-09-25T03:43:53.129+00:00",
        "toolUuid": "8148edcd-7d1a-4d33-afa7-28a3e2f920b9"
      },
      {
        "aiAgentId": 1047,
        "agentName": "UI-REVIEW Remittance batch review (very long template)",
        "description": "UI-REVIEW test prompt with a ~12,000-character template, three variables and JSON output.",
        "provider": "Ollama",
        "apiEndpoint": "redacted",
        "apiKeyConfigured": false,
        "model": "gemma3:1b",
        "targetFileTypes": "ui-review,finance,long",
        "instructions": "You are a careful finance reviewer. Be concise. Never invent numbers.",
        "status": "Active",
        "jsonMode": true,
        "dateCreated": "2026-09-25T03:43:53.048+00:00",
        "toolUuid": "be0ed742-0327-4068-bdc9-5ed8e1f07d4c"
      }
    ]
  },
  "POST /sourceTask.json/listSourceTask": {
    "status": "SUCCESS",
    "message": "SourceTask successfully ",
    "data": [
      {
        "createdByName": "Casey Baseline",
        "createdBy": 4537,
        "taskDetailId": 1854,
        "tenantId": 2924,
        "taskName": "Reference: CSV check and summarise",
        "taskStatus": "Active",
        "pipelineId": "REF_CSV_CHECK_V1",
        "taskPayload": "<csvCheck><inputKey>reference/input/sample.csv</inputKey><outputPrefix>reference/output</outputPrefix><maxRejectPercent>50</maxRejectPercent><requiredColumns>id,name</requiredColumns><numericColumns>amount</numericColumns><deleteInput>false</deleteInput><bucket>etl-bucket</bucket></csvCheck>",
        "bucket": "etl-bucket",
        "sourceTaskType": {
          "sourceTaskTypeId": 11831,
          "serviceName": "service-1 reference worker",
          "description": "service-1 worker runtime reference pipeline (WORKER-CONTRACT.md)",
          "queueTopicPartition": "topic=etl.reference&partitions=[*]",
          "status": "Active"
        },
        "totalLinksJobs": 1
      },
      {
        "createdByName": "Casey Baseline",
        "updatedByName": "Casey Baseline",
        "createdBy": 4537,
        "taskDetailId": 1855,
        "tenantId": 2924,
        "taskName": "UI-REVIEW Clean customers CSV check",
        "taskStatus": "Active",
        "homePageId": "UI-REVIEW Finance home",
        "pipelineId": "REF_CSV_CHECK_V1",
        "groupId": "UI-REVIEW Finance checks",
        "taskPayload": "<csvCheck><inputKey>ui-review/inputs/clean-customers.csv</inputKey><outputPrefix>ui-review/output/clean-customers</outputPrefix><maxRejectPercent>10</maxRejectPercent><requiredColumns>id,name</requiredColumns><numericColumns>amount</numericColumns><deleteInput>false</deleteInput><bucket>etl-bucket</bucket></csvCheck>",
        "bucket": "etl-bucket",
        "sourceTaskType": {
          "sourceTaskTypeId": 11831,
          "serviceName": "service-1 reference worker",
          "description": "service-1 worker runtime reference pipeline (WORKER-CONTRACT.md)",
          "queueTopicPartition": "topic=etl.reference&partitions=[*]",
          "status": "Active"
        },
        "totalLinksJobs": 4
      }
    ],
    "paging": {
      "totalRecord": 9,
      "pageSize": 1000,
      "currentPage": 1
    }
  },
  "GET /sourceTask.json/fetchSourceTaskWithSourceTaskId": {
    "status": "SUCCESS",
    "message": "SourceTask found with 1854.",
    "data": {
      "taskDetailId": 1854,
      "tenantId": 2924,
      "taskName": "Reference: CSV check and summarise",
      "taskStatus": "Active",
      "pipelineId": "REF_CSV_CHECK_V1",
      "taskPayload": "<csvCheck><inputKey>reference/input/sample.csv</inputKey><outputPrefix>reference/output</outputPrefix><maxRejectPercent>50</maxRejectPercent><requiredColumns>id,name</requiredColumns><numericColumns>amount</numericColumns><deleteInput>false</deleteInput><bucket>etl-bucket</bucket></csvCheck>",
      "sourceTaskType": {
        "sourceTaskTypeId": 11831,
        "serviceName": "service-1 reference worker",
        "description": "service-1 worker runtime reference pipeline (WORKER-CONTRACT.md)",
        "queueTopicPartition": "topic=etl.reference&partitions=[*]",
        "status": "Active"
      },
      "xmlTagsInfo": [
        {
          "taskPayloadId": 4804,
          "tagKey": "csvCheck",
          "tagParent": "csvCheck",
          "tagValue": null
        },
        {
          "taskPayloadId": 4805,
          "tagKey": "inputKey",
          "tagParent": "csvCheck",
          "tagValue": "reference/input/sample.csv"
        }
      ]
    }
  },
  "GET /kafkaConnectionProfile.json/fetchAllProfiles": {
    "status": "SUCCESS",
    "message": "Kafka connection profiles fetched successfully.",
    "data": [
      {
        "kafkaConnectionProfileId": 1009,
        "profileName": "Platform Local Broker [PF]",
        "environmentLabel": "local",
        "securityProtocol": "PLAINTEXT",
        "saslPasswordConfigured": false,
        "sslKeystorePasswordConfigured": false,
        "sslKeyPasswordConfigured": false,
        "sslTruststorePasswordConfigured": false,
        "sslEndpointIdentificationAlgorithm": "redacted",
        "isDefault": true,
        "platform": true,
        "readOnly": true,
        "status": "Active",
        "connectionStatus": "SUCCESS",
        "lastTestedAt": "2026-09-25T02:27:27.698+00:00",
        "dateCreated": "2026-08-27T22:19:35.631+00:00"
      }
    ]
  },
  "GET /setting.json/taskReferences?kind=TASK_GROUP": {
    "status": "SUCCESS",
    "message": "Data fetch successfully.",
    "data": [
      {
        "id": 1283,
        "tenantId": 2924,
        "kind": "TASK_GROUP",
        "name": "UI-REVIEW Finance checks",
        "value": "FIN",
        "description": "UI-REVIEW task group.",
        "createdAt": "2026-09-25T03:44:26.068Z",
        "createdByName": "Casey Baseline",
        "usedByTasks": 2
      },
      {
        "id": 1284,
        "tenantId": 2924,
        "kind": "TASK_GROUP",
        "name": "UI-REVIEW Zürich – 東京 ✓ shared-service centre reconciliation group with a long name",
        "createdAt": "2026-09-25T03:44:26.103Z",
        "createdByName": "Casey Baseline",
        "usedByTasks": 1
      }
    ]
  },
  "GET /setting.json/taskReferences?kind=HOME_PAGE": {
    "status": "SUCCESS",
    "message": "Data fetch successfully.",
    "data": [
      {
        "id": 1285,
        "tenantId": 2924,
        "kind": "HOME_PAGE",
        "name": "UI-REVIEW Finance home",
        "value": "https://example.com/finance",
        "description": "UI-REVIEW home page.",
        "createdAt": "2026-09-25T03:44:26.128Z",
        "createdByName": "Casey Baseline",
        "usedByTasks": 1
      }
    ]
  },
  "GET /setting.json/topics": {
    "status": "SUCCESS",
    "message": "1 topic(s).",
    "data": [
      {
        "status": "Active",
        "queueTopicPartition": "topic=etl.reference&partitions=[*]",
        "sourceTaskTypeId": 11831,
        "serviceName": "service-1 reference worker",
        "tenantId": 2924,
        "kafkaConnectionProfileId": null
      }
    ]
  },
  "GET /pipeline.json/list": {
    "status": "SUCCESS",
    "message": "1 pipeline(s).",
    "data": {
      "summary": {
        "total": 1,
        "topics": 1,
        "active": 1,
        "untopped": 0,
        "fields": 7
      },
      "rows": [
        {
          "pipelineKey": 100167,
          "pipelineId": "REF_CSV_CHECK_V1",
          "pipelineName": "Reference: CSV check and summarise",
          "description": "service-1 reference pipeline. Reads a CSV, validates it, writes summary.json and rejects.csv.",
          "tenantId": 2924,
          "sourceTaskTypeId": 11831,
          "topicName": "service-1 reference worker",
          "kafkaTopic": "etl.reference",
          "status": "Active",
          "dateCreated": "2026-09-24T22:06:11.852167",
          "createdBy": 4537,
          "createdByName": "Casey Baseline",
          "fieldCount": 7,
          "requiredCount": 3
        }
      ]
    },
    "paging": {
      "totalRecord": 1,
      "pageSize": 50,
      "currentPage": 1
    }
  },
  "GET /pipeline.json/fields": {
    "status": "SUCCESS",
    "message": "7 field(s).",
    "data": [
      {
        "pipelineFieldId": 100168,
        "tagKey": "inputKey",
        "label": "Input CSV (relative to the workspace)",
        "fieldType": "text",
        "required": true,
        "position": 0
      },
      {
        "pipelineFieldId": 100169,
        "tagKey": "outputPrefix",
        "label": "Output prefix",
        "fieldType": "text",
        "required": true,
        "defaultValue": "reference/output",
        "position": 1
      }
    ]
  },
  "GET /pipeline.json/definition": {
    "status": "SUCCESS",
    "message": "Pipeline found.",
    "data": {
      "pipelineKey": 100167,
      "pipelineId": "REF_CSV_CHECK_V1",
      "pipelineName": "Reference: CSV check and summarise",
      "description": "service-1 reference pipeline. Reads a CSV, validates it, writes summary.json and rejects.csv.",
      "tenantId": 2924,
      "sourceTaskTypeId": 11831,
      "topicName": "service-1 reference worker",
      "kafkaTopic": "etl.reference",
      "status": "Active",
      "dateCreated": "2026-09-24T22:06:11.852167",
      "createdBy": 4537,
      "fields": [
        {
          "pipelineFieldId": 100168,
          "tagKey": "inputKey",
          "label": "Input CSV (relative to the workspace)",
          "fieldType": "text",
          "required": true,
          "position": 0
        },
        {
          "pipelineFieldId": 100169,
          "tagKey": "outputPrefix",
          "label": "Output prefix",
          "fieldType": "text",
          "required": true,
          "defaultValue": "reference/output",
          "position": 1
        }
      ]
    }
  },
  "GET /pipeline.json/listForTopic": {
    "status": "SUCCESS",
    "message": "1 pipeline(s).",
    "data": [
      {
        "pipelineKey": 100167,
        "pipelineId": "REF_CSV_CHECK_V1",
        "pipelineName": "Reference: CSV check and summarise",
        "description": "service-1 reference pipeline. Reads a CSV, validates it, writes summary.json and rejects.csv.",
        "tenantId": 2924,
        "sourceTaskTypeId": 11831,
        "topicName": "service-1 reference worker",
        "kafkaTopic": "etl.reference",
        "status": "Active",
        "dateCreated": "2026-09-24T22:06:11.852167",
        "createdBy": 4537,
        "fields": [
          {
            "pipelineFieldId": 100168,
            "tagKey": "inputKey",
            "label": "Input CSV (relative to the workspace)",
            "fieldType": "text",
            "required": true,
            "position": 0
          },
          {
            "pipelineFieldId": 100169,
            "tagKey": "outputPrefix",
            "label": "Output prefix",
            "fieldType": "text",
            "required": true,
            "defaultValue": "reference/output",
            "position": 1
          }
        ]
      }
    ]
  },
  "POST /message.json/fetchLogs": {
    "status": "SUCCESS",
    "message": "MessageQ successfully ",
    "data": {
      "jobStatusStatistic": [
        {
          "name": "SKIP",
          "value": 7
        },
        {
          "name": "FAILED",
          "value": 10
        }
      ],
      "sourceJobQueues": [
        {
          "jobQueueId": 7382,
          "skipTime": "2026-10-02T09:30:00",
          "jobStatus": "Skip",
          "jobId": 2838,
          "jobSend": false,
          "jobStatusMessage": "Job 2838 skip, by user action.",
          "skipManual": true,
          "dateCreated": "2026-09-28T20:11:08.580+00:00"
        },
        {
          "jobQueueId": 7381,
          "startTime": "2026-09-28T02:02:27",
          "endTime": "2026-09-28T02:02:37",
          "jobStatus": "Completed",
          "jobId": 2835,
          "jobSend": true,
          "jobStatusMessage": "Checked 2000 row(s) of ui-review/inputs/ledger-2000-rows.csv: 1943 accepted, 57 rejected. Summary: tenant-2924/ui-review/output/ledger/run-7381/summary.json",
          "dateCreated": "2026-09-28T07:02:27.591+00:00"
        }
      ]
    }
  },
  "GET /report.json/runs": {
    "status": "SUCCESS",
    "message": "50 run(s).",
    "data": {
      "task": [
        "UI-REVIEW Ledger 2,000 rows with a long notes column",
        "UI-REVIEW Zürich – 東京 ✓ quarterly reconciliation of vendor remittance advice against purchase orders, goods receipts and invoices (unicode)"
      ],
      "status": [
        "Completed",
        "Skip"
      ],
      "owner": [
        "Claude Demo Admin",
        "Alex"
      ],
      "day": [
        "2026-09-28",
        "2026-09-27"
      ],
      "tenant": [
        "Claude Demo 75a611b4"
      ],
      "rows": [
        [
          0,
          0
        ],
        [
          0,
          0
        ]
      ],
      "truncated": false
    }
  },
  "GET /aiPrompt.json/usage": {
    "status": "SUCCESS",
    "message": "4 prompt(s) used.",
    "data": [
      {
        "tokensIn": 874,
        "tokensOut": 122,
        "promptId": 1048,
        "calls": 3,
        "promptName": "UI-REVIEW Summarise a CSV run in one paragraph",
        "failed": 0,
        "tries": 3,
        "medianMs": 2378,
        "lastAt": "2026-09-28T22:52:24.110+00:00"
      },
      {
        "tokensIn": 0,
        "tokensOut": 0,
        "promptId": 1049,
        "calls": 3,
        "promptName": "UI-REVIEW Zürich – 東京 ✓ draft prompt (never activated) with a deliberately long name for truncation checks in the prompt list",
        "failed": 3,
        "tries": 3,
        "medianMs": 85,
        "lastAt": "2026-09-28T21:11:48.441+00:00"
      }
    ]
  },
  "GET /documentConverter.json/fetchAllTasks": {
    "status": "SUCCESS",
    "message": "Data fetched successfully.",
    "data": [
      {
        "documentConverterTaskId": 1034,
        "tenantId": 2924,
        "taskName": "UI-REVIEW notes converted ✓ Zürich",
        "inputFileName": "UI-REVIEW-notes.md",
        "inputFormat": "md",
        "inputContentType": "application/octet-stream",
        "inputFileSize": 48,
        "outputFormat": "pdf",
        "outputFileName": "UI-REVIEW-notes.pdf",
        "outputContentType": "application/pdf",
        "outputFileSize": 27892,
        "bucketName": "ui-review-s3",
        "targetFolder": "UI-REVIEW converted",
        "inputStorageKey": "UI-REVIEW converted/1034/input/UI-REVIEW-notes.md",
        "outputStorageKey": "UI-REVIEW converted/1034/output/UI-REVIEW-notes.pdf",
        "status": "Active",
        "dateCreated": "2026-09-25T04:06:26.530+00:00"
      }
    ]
  },
  "GET /documentConverter.json/supportedFormats": {
    "status": "SUCCESS",
    "message": "Supported formats fetched successfully.",
    "data": [
      {
        "key": "TEXT",
        "label": "Text Document",
        "inputFormats": [
          "doc",
          "docx"
        ],
        "outputFormats": [
          "doc",
          "docx"
        ]
      },
      {
        "key": "SPREADSHEET",
        "label": "Spreadsheet",
        "inputFormats": [
          "csv",
          "fods"
        ],
        "outputFormats": [
          "csv",
          "fods"
        ]
      }
    ]
  },
  "GET /storage.json/buckets": {
    "status": "SUCCESS",
    "message": "Buckets fetched successfully.",
    "data": [
      {
        "label": "UI-REVIEW LocalStack S3 (fake keys)",
        "bucket": "ui-review-s3",
        "provider": "S3",
        "bucketName": "ui-review-2924",
        "region": "us-east-1",
        "description": "UI-REVIEW test data. LocalStack S3 emulator; the keys are obviously fake (LocalStack does not check them).",
        "connectionStatus": "SUCCESS",
        "dateCreated": "2026-09-24T22:39:41.53",
        "createdByName": "Casey Baseline"
      }
    ]
  },
  "GET /storage.json/listObjects": {
    "status": "SUCCESS",
    "message": "Objects fetched successfully.",
    "data": {
      "objects": [
        {
          "name": "UI-REVIEW converted",
          "key": "UI-REVIEW converted/",
          "folder": true
        },
        {
          "name": "UI-REVIEW uploads",
          "key": "UI-REVIEW uploads/",
          "folder": true
        }
      ]
    }
  },
  "GET /aiPrompt.json/list": {
    "status": "SUCCESS",
    "message": "5 prompt(s).",
    "data": [
      {
        "promptId": 1049,
        "promptUuid": "5a2c6b6b-c25d-40d0-a8bb-3d1bcdd81d6f",
        "tenantId": 2924,
        "name": "UI-REVIEW Zürich – 東京 ✓ draft prompt (never activated) with a deliberately long name for truncation checks in the prompt list",
        "description": "UI-REVIEW draft: saved without activating.",
        "connectionId": 1047,
        "connectionName": "Local Ollama",
        "provider": "Ollama",
        "model": "llama3.2:1b",
        "effectiveModel": "llama3.2:1b",
        "systemInstructions": "Reply in the language of the input.",
        "userTemplate": "Translate the city name {{city}} into English and give its country. Page: {{url}}; rows: {{rows}}",
        "variables": [
          {
            "name": "city",
            "type": "text",
            "required": true,
            "sample": "東京",
            "description": null
          },
          {
            "name": "url",
            "type": "url",
            "required": false,
            "sample": "https://example.com/cities",
            "description": null
          }
        ],
        "outputMode": "text",
        "temperature": 0.7,
        "maxTokens": 200,
        "tags": "ui-review,draft,unicode",
        "version": 1,
        "status": "Inactive",
        "runCount": 3,
        "pipelineCount": 0,
        "lastRunAt": "2026-09-28T21:11:48.441+00:00",
        "lastRunStatus": "failed",
        "dateCreated": "2026-09-25T03:43:53.162+00:00",
        "createdBy": 4537,
        "createdByName": "Casey Baseline"
      },
      {
        "promptId": 1048,
        "promptUuid": "8148edcd-7d1a-4d33-afa7-28a3e2f920b9",
        "tenantId": 2924,
        "name": "UI-REVIEW Summarise a CSV run in one paragraph",
        "description": "UI-REVIEW: v2 adds a tone variable.",
        "connectionName": "Local Ollama (default)",
        "provider": "Ollama",
        "effectiveModel": "gemma3:1b",
        "userTemplate": "Summarise this run for an operator in one short paragraph, in a {{tone}} tone:\n\n{{summary}}",
        "variables": [
          {
            "name": "summary",
            "type": "text",
            "required": true,
            "sample": "Checked 40 rows: 40 accepted, 0 rejected.",
            "description": null
          },
          {
            "name": "tone",
            "type": "text",
            "required": false,
            "sample": "neutral",
            "description": null
          }
        ],
        "outputMode": "text",
        "temperature": 0.3,
        "maxTokens": 300,
        "tags": "ui-review",
        "version": 2,
        "status": "Active",
        "runCount": 3,
        "pipelineCount": 0,
        "lastRunAt": "2026-09-28T22:52:24.110+00:00",
        "lastRunStatus": "ok",
        "dateCreated": "2026-09-25T03:43:53.129+00:00",
        "createdBy": 4537,
        "createdByName": "Casey Baseline",
        "updatedByName": "Casey Baseline"
      }
    ]
  },
  "GET /aiPrompt.json/get": {
    "status": "SUCCESS",
    "message": "Data found.",
    "data": {
      "promptId": 1049,
      "promptUuid": "5a2c6b6b-c25d-40d0-a8bb-3d1bcdd81d6f",
      "tenantId": 2924,
      "name": "UI-REVIEW Zürich – 東京 ✓ draft prompt (never activated) with a deliberately long name for truncation checks in the prompt list",
      "description": "UI-REVIEW draft: saved without activating.",
      "connectionId": 1047,
      "connectionName": "Local Ollama",
      "provider": "Ollama",
      "model": "llama3.2:1b",
      "effectiveModel": "llama3.2:1b",
      "systemInstructions": "Reply in the language of the input.",
      "userTemplate": "Translate the city name {{city}} into English and give its country. Page: {{url}}; rows: {{rows}}",
      "variables": [
        {
          "name": "city",
          "type": "text",
          "required": true,
          "sample": "東京",
          "description": null
        },
        {
          "name": "url",
          "type": "url",
          "required": false,
          "sample": "https://example.com/cities",
          "description": null
        }
      ],
      "outputMode": "text",
      "temperature": 0.7,
      "maxTokens": 200,
      "tags": "ui-review,draft,unicode",
      "version": 1,
      "status": "Inactive",
      "runCount": 3,
      "pipelineCount": 0,
      "lastRunAt": "2026-09-28T21:11:48.441+00:00",
      "lastRunStatus": "failed",
      "dateCreated": "2026-09-25T03:43:53.162+00:00",
      "createdBy": 4537,
      "createdByName": "Casey Baseline"
    }
  },
  "GET /aiPrompt.json/runs": {
    "status": "SUCCESS",
    "message": "3 run(s).",
    "data": [
      {
        "runId": 1973,
        "tenantId": 2924,
        "promptId": 1049,
        "promptVersion": 1,
        "connectionId": 1047,
        "kind": "try",
        "renderedInput": "system: Reply in the language of the input.\n\nuser: Translate the city name 東京 into English and give its country. Page: https://example.com/cities; rows: 6",
        "latencyMs": 182,
        "attempts": 1,
        "status": "failed",
        "error": "HTTP 404: {\"error\":\"model 'llama3.2:1b' not found\"}",
        "dateCreated": "2026-09-28T21:11:48.441+00:00",
        "createdBy": 1000
      },
      {
        "runId": 1969,
        "tenantId": 2924,
        "promptId": 1049,
        "promptVersion": 1,
        "connectionId": 1047,
        "kind": "try",
        "renderedInput": "system: Reply in the language of the input.\n\nuser: Translate the city name 東京 into English and give its country. Page: https://example.com/cities; rows: 6",
        "latencyMs": 46,
        "attempts": 1,
        "status": "failed",
        "error": "HTTP 404: {\"error\":\"model 'llama3.2:1b' not found\"}",
        "dateCreated": "2026-09-25T17:29:21.302+00:00",
        "createdBy": 1000
      }
    ],
    "paging": {
      "totalRecord": 3,
      "pageSize": 10,
      "currentPage": 1
    }
  },
  "GET /aiConnection.json/list": {
    "status": "SUCCESS",
    "message": "2 connection(s).",
    "data": [
      {
        "connectionId": 1048,
        "tenantId": 2924,
        "name": "UI-REVIEW Zürich – 東京 ✓ unreachable Ollama with a deliberately long connection name for truncation",
        "provider": "Ollama",
        "apiEndpoint": "redacted",
        "apiKeyConfigured": false,
        "defaultModel": "gemma3:1b",
        "isDefault": false,
        "maxConcurrency": 4,
        "dailyTokenBudget": 50000,
        "status": "Active",
        "lastTestedAt": "2026-09-25T04:02:33.219+00:00",
        "lastTestOk": false,
        "lastTestMessage": "Network is unreachable",
        "promptCount": 0,
        "runs30d": 0,
        "tokensIn30d": 0,
        "tokensOut30d": 0,
        "tokensToday": 0,
        "dateCreated": "2026-09-25T04:02:28.589+00:00",
        "createdBy": 4537,
        "createdByName": "Casey Baseline",
        "updatedByName": "Casey Baseline"
      },
      {
        "connectionId": 1047,
        "tenantId": 2924,
        "name": "Local Ollama",
        "provider": "Ollama",
        "apiEndpoint": "redacted",
        "apiKeyConfigured": false,
        "defaultModel": "gemma3:1b",
        "isDefault": true,
        "maxConcurrency": 4,
        "status": "Active",
        "lastTestedAt": "2026-09-25T01:01:51.407+00:00",
        "lastTestOk": true,
        "lastTestMessage": "Reached the provider; 5 model(s) listed.",
        "models": [
          "gemma3:1b",
          "gemma3:4b"
        ],
        "promptCount": 4,
        "runs30d": 9,
        "tokensIn30d": 1040,
        "tokensOut30d": 223,
        "tokensToday": 73,
        "dateCreated": "2026-09-22T22:23:47.625+00:00",
        "createdBy": 4537,
        "createdByName": "Casey Baseline",
        "updatedByName": "Casey Baseline"
      }
    ]
  },
  "GET /pageAccess.json/pages": {
    "status": "SUCCESS",
    "message": "Pages fetched.",
    "data": [
      {
        "route": "/operations/jobs",
        "section": "Operations",
        "label": "Source Jobs",
        "key": "jobs"
      },
      {
        "route": "/operations/tasks",
        "section": "Operations",
        "label": "Source Tasks",
        "key": "tasks"
      }
    ]
  },
  "GET /pageAccess.json/listProfiles": {
    "status": "SUCCESS",
    "message": "Access profiles fetched.",
    "data": [
      {
        "pageAccessProfileId": 1044,
        "tenantId": 2924,
        "profileName": "UI-REVIEW Analysts — Zürich – 東京 ✓ finance analytics and AI prompt authors (long name)",
        "description": "UI-REVIEW test profile: analytics, dashboards, reports, AI prompts and the document converter.",
        "defaultProfile": false,
        "status": "Active",
        "pageKeys": [
          "reports",
          "analytics"
        ],
        "userCount": 0,
        "userNames": [],
        "dateCreated": "2026-09-25T03:45:06.611+00:00",
        "createdByName": "Casey Baseline"
      },
      {
        "pageAccessProfileId": 1045,
        "tenantId": 2924,
        "profileName": "UI-REVIEW No pages",
        "defaultProfile": false,
        "status": "Active",
        "pageKeys": [],
        "userCount": 0,
        "userNames": [],
        "dateCreated": "2026-09-25T03:45:06.637+00:00",
        "dateUpdated": "2026-09-25T04:07:40.598+00:00",
        "createdByName": "Casey Baseline",
        "updatedByName": "Casey Baseline"
      }
    ]
  },
  "GET /pageAccess.json/listPeople": {
    "status": "SUCCESS",
    "message": "People fetched.",
    "data": [
      {
        "appUserId": 4597,
        "fullName": "Casey Baseline",
        "username": "person@example.com",
        "position": "Software Engineer",
        "status": "Active",
        "pageKeys": [
          "jobs",
          "tasks"
        ],
        "allowedExceptions": [],
        "withheldExceptions": []
      }
    ]
  },
  "GET /tenant.json/listTenants": {
    "status": "SUCCESS",
    "message": "Tenants fetched successfully.",
    "data": [
      {
        "createdByName": "Casey Baseline",
        "createdBy": 4536,
        "tenantId": 2924,
        "uuid": "24714c49-3284-4f21-b0d2-c765d23b86c9",
        "tenantName": "Claude Demo 75a611b4",
        "tenantCode": "claude-demo-75a611b4",
        "status": "Active",
        "dateCreated": "2026-09-22T22:23:32.844+00:00",
        "userCount": 2,
        "kafkaProfileCount": 0,
        "bucketCount": 1,
        "sourceTaskTypeCount": 1,
        "sourceTaskCount": 9,
        "pipelineCount": 1,
        "sourceJobCount": 15,
        "adminName": "Casey Baseline",
        "adminEmail": "person@example.com"
      },
      {
        "updatedByName": "Casey Baseline",
        "tenantId": 2900,
        "uuid": "7fd7d753-4802-4c63-a9e2-31f3c348c549",
        "tenantName": "Default",
        "tenantCode": "default",
        "status": "Active",
        "dateCreated": "2026-09-16T02:15:18.088+00:00",
        "userCount": 0,
        "kafkaProfileCount": 0,
        "bucketCount": 0,
        "sourceTaskTypeCount": 2,
        "sourceTaskCount": 0,
        "pipelineCount": 0,
        "sourceJobCount": 0
      }
    ]
  },
  "GET /analyticsDataset.json/fetchAllDatasets": {
    "status": "SUCCESS",
    "message": "Data fetched successfully.",
    "data": [
      {
        "createdByName": "Casey Baseline",
        "createdBy": 4537,
        "analyticsDatasetId": 1006,
        "tenantId": 2924,
        "datasetName": "UI-REVIEW Journey sales (flows)",
        "connectionAlias": "ui-review-s3",
        "storageConnectionId": 1109,
        "datasetPath": "data/UI-REVIEW-journey-sales.csv",
        "datasetFormat": "CSV",
        "dateCreated": "2026-09-25T04:04:01.989+00:00"
      },
      {
        "createdByName": "Casey Baseline",
        "createdBy": 4537,
        "analyticsDatasetId": 1005,
        "tenantId": 2924,
        "datasetName": "UI-REVIEW bad path test",
        "connectionAlias": "ui-review-s3",
        "storageConnectionId": 1109,
        "datasetPath": "does/not/exist.csv",
        "datasetFormat": "CSV",
        "dateCreated": "2026-09-25T04:01:48.326+00:00"
      }
    ]
  },
  "GET /analyticsWorkspace.json/fetchAllDashboards": {
    "status": "SUCCESS",
    "message": "Data fetched successfully.",
    "data": [
      {
        "createdByName": "Casey Baseline",
        "createdBy": 4537,
        "analyticsDashboardId": 1379,
        "tenantId": 2924,
        "dashboardName": "UI-REVIEW Empty dashboard with a very long name to check how the header, the picker and the list cope with it — Zürich – 東京 ✓",
        "dateCreated": "2026-09-25T03:43:02.920+00:00"
      },
      {
        "createdByName": "Casey Baseline",
        "createdBy": 4537,
        "analyticsDashboardId": 1378,
        "tenantId": 2924,
        "dashboardName": "UI-REVIEW Finance overview",
        "dashboardDescription": "UI-REVIEW test dashboard: customers and ledger figures from the LocalStack test bucket.",
        "dateCreated": "2026-09-25T03:43:02.887+00:00"
      }
    ]
  },
  "GET /analyticsWorkspace.json/fetchAllAnalyses": {
    "status": "SUCCESS",
    "message": "Data fetched successfully.",
    "data": [
      {
        "createdByName": "Casey Baseline",
        "createdBy": 4537,
        "analyticsAnalysisId": 3028,
        "tenantId": 2924,
        "analysisName": "UI-REVIEW Journey sales by region (flows)",
        "connectionAlias": "ui-review-s3",
        "storageConnectionId": 1109,
        "datasetPath": "data/UI-REVIEW-journey-sales.csv",
        "visualizationType": "table",
        "analysisConfig": "{\"dimensions\":[\"region\"],\"grains\":[null],\"measure\":{\"aggregation\":\"SUM\",\"field\":\"amount\"},\"filters\":{\"op\":\"AND\",\"clauses\":[]},\"topN\":null,\"sort\":{\"by\":\"MEASURE\",\"direction\":\"DESC\"}}",
        "dateCreated": "2026-09-25T04:05:09.220+00:00"
      },
      {
        "createdByName": "Casey Baseline",
        "createdBy": 4537,
        "analyticsAnalysisId": 3027,
        "tenantId": 2924,
        "analysisName": "UI-REVIEW Big amounts (> 1,000) by city — filtered",
        "connectionAlias": "ui-review-s3",
        "storageConnectionId": 1109,
        "datasetPath": "data/csv/small/UI-REVIEW-customers-small.csv",
        "visualizationType": "bar",
        "analysisConfig": "{\"dimensions\":[\"city\"],\"grains\":[null],\"measure\":{\"aggregation\":\"SUM\",\"field\":\"amount\"},\"filters\":{\"op\":\"AND\",\"clauses\":[{\"field\":\"amount\",\"operator\":\"GT\",\"value\":1000}]},\"topN\":null,\"sort\":{\"by\":\"MEASURE\",\"direction\":\"DESC\"}}",
        "dateCreated": "2026-09-25T03:43:02.851+00:00"
      }
    ]
  },
  "GET /analyticsLibrary.json/fetchAllQueries": {
    "status": "SUCCESS",
    "message": "Data fetched successfully.",
    "data": [
      {
        "createdByName": "Casey Baseline",
        "createdBy": 4537,
        "analyticsQueryId": 1028,
        "tenantId": 2924,
        "queryName": "UI-REVIEW Rejected-looking ledger rows",
        "connectionAlias": "ui-review-s3",
        "storageConnectionId": 1109,
        "datasetPath": "data/csv/large/UI-REVIEW-ledger-2000-rows.csv",
        "queryText": "select id, name, amount, city, length(notes) as notes_length\nfrom dataset\nwhere name is null or try_cast(amount as double) is null\norder by id\nlimit 200",
        "dateCreated": "2026-09-25T03:42:46.081+00:00"
      }
    ]
  },
  "GET /storageConnection.json/fetchAllConnections": {
    "status": "SUCCESS",
    "message": "Data found.",
    "data": [
      {
        "createdBy": 4537,
        "createdByName": "Casey Baseline",
        "updatedByName": "Casey Baseline",
        "storageConnectionId": 1109,
        "tenantId": 2924,
        "connectionName": "UI-REVIEW LocalStack S3 (fake keys)",
        "alias": "ui-review-s3",
        "provider": "S3",
        "description": "UI-REVIEW test data. LocalStack S3 emulator; the keys are obviously fake (LocalStack does not check them).",
        "bucketName": "ui-review-2924",
        "endpoint": "redacted",
        "region": "us-east-1",
        "accessKey": "redacted",
        "secretKeyConfigured": true,
        "azureConnectionStringConfigured": false,
        "passwordConfigured": false,
        "passiveMode": true,
        "implicitTls": false,
        "isDefault": false,
        "status": "Active",
        "connectionStatus": "SUCCESS",
        "lastTestedAt": "2026-09-25T04:07:47.381+00:00",
        "lastTestMessage": "Connected -- ui-review-2924 is readable (returned objects).",
        "dateCreated": "2026-09-25T03:39:41.530+00:00"
      }
    ]
  }
};
