import { describe, it, afterEach } from 'vitest';
import { useMemoryStorage } from '../shared/testing/memory-storage';
import { TU_PAGES, Visit, click, closeOverlays, detailsOf, overlay, pin, restoreClock, visit } from './harness';
import { PINNED } from './pinned/task-registry';

/**
 * MIG-250 characterisation baseline: Configuration › Task Registry -- the registry table (every step task, and every
 * pipeline as a Legacy task), its filters, a task's side panel, a Legacy row's panel and its way into the pipeline
 * dialog, and an administrator's switch. The pipeline dialog and the AI step panel themselves stay pinned in
 * pipelines (reached from here since MIG-250).
 */
const FILE = 'task-registry';

/** The Task Registry as Core (MIG-231, media-extraction 2214c52) answered it on 2026-09-29, input and output schemas cut. */
const REGISTRY_TASKS = { status: "SUCCESS", message: "17 step task(s) and 2 legacy pipeline(s).", data: [
  {"code": "aggregate", "name": "Aggregate", "kind": "Process", "description": "Groups rows by columns and computes count, count_distinct, sum, avg, min, max, first or last.", "configSchema": {"type": "object", "properties": {"groupBy": {"type": "array", "items": {"type": "string", "minLength": 1, "maxLength": 128, "format": "column"}, "maxItems": 20, "title": "Group by", "description": "Empty: one row for all the input."}, "aggregations": {"type": "array", "items": {"type": "object", "properties": {"op": {"type": "string", "enum": ["count", "count_distinct", "sum", "avg", "min", "max", "first", "last"], "title": "Compute"}, "column": {"type": "string", "maxLength": 128, "title": "Of column", "format": "column", "description": "Every operation but count needs one."}, "as": {"type": "string", "minLength": 1, "maxLength": 128, "title": "As column"}}, "additionalProperties": false, "required": ["op", "as"]}, "minItems": 1, "maxItems": 50, "title": "Aggregations"}}, "additionalProperties": false, "required": ["aggregations"]}, "backingService": "core", "retry": {"maxAttempts": 1, "delaySeconds": 0}, "timeoutSeconds": null, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": true, "runsInEngine": true, "enabled": true, "overridden": false, "available": true, "disabledReason": null},
  {"code": "enrich", "name": "Enrich", "kind": "Process", "description": "Calls a saved API request per row (integration-service's runner) and adds fields of its answer as columns.", "configSchema": {"type": "object", "properties": {"requestId": {"type": "integer", "minimum": 1, "title": "API request", "format": "api-request", "description": "A request saved in the workspace's API collections (integration-service)."}, "environmentId": {"type": "integer", "minimum": 1, "title": "Environment", "format": "api-environment", "description": "The environment whose variables the request runs with; none for the collection's default."}, "version": {"type": "integer", "minimum": 1, "title": "Collection version", "description": "Pin the request to a published collection version; empty for the request as it is now."}, "variables": {"type": "object", "additionalProperties": {"type": "string", "format": "template"}, "title": "Variables", "description": "Request variables by name, filled from the row: {{customer_id}}."}, "fields": {"type": "array", "items": {"type": "object", "properties": {"path": {"type": "string", "minLength": 1, "maxLength": 255, "title": "From the answer at", "description": "A dot path into the answer's body: data.score."}, "target": {"type": "string", "minLength": 1, "maxLength": 128, "title": "As column"}}, "additionalProperties": false, "required": ["path", "target"]}, "minItems": 1, "maxItems": 50, "title": "Fields"}, "onError": {"type": "string", "enum": ["fail", "skip", "null"], "title": "When a call fails", "default": "fail", "description": "fail the step, skip the row, or keep it with the fields empty."}, "maxCalls": {"type": "integer", "minimum": 1, "maximum": 500, "title": "At most calls", "default": 100}}, "additionalProperties": false, "required": ["requestId", "fields"]}, "backingService": "integration-service", "retry": {"maxAttempts": 1, "delaySeconds": 0}, "timeoutSeconds": 1800, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": true, "runsInEngine": true, "enabled": false, "overridden": false, "available": false, "disabledReason": "integration-service's internal pipeline endpoints are not deployed yet (process.pipeline.integration.internal-endpoints is off)"},
  {"code": "filter", "name": "Filter", "kind": "Process", "description": "Keeps the rows that meet all (or any) of its conditions.", "configSchema": {"type": "object", "properties": {"match": {"type": "string", "enum": ["all", "any"], "title": "Keep a row that meets", "default": "all"}, "conditions": {"type": "array", "items": {"type": "object", "properties": {"column": {"type": "string", "minLength": 1, "maxLength": 128, "title": "Column", "format": "column"}, "operator": {"type": "string", "enum": ["eq", "ne", "gt", "gte", "lt", "lte", "contains", "starts_with", "ends_with", "in", "not_in", "is_null", "not_null", "is_empty", "not_empty"], "title": "Is"}, "value": {"type": ["string", "number", "boolean", "null"], "title": "Value"}, "values": {"type": "array", "items": {"type": ["string", "number", "boolean", "null"]}, "maxItems": 1000, "title": "Values", "description": "in / not_in."}, "ignoreCase": {"type": "boolean", "title": "Ignore case", "default": false}}, "additionalProperties": false, "required": ["column", "operator"]}, "minItems": 1, "maxItems": 50, "title": "Conditions"}}, "additionalProperties": false, "required": ["conditions"]}, "backingService": "core", "retry": {"maxAttempts": 1, "delaySeconds": 0}, "timeoutSeconds": null, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": true, "runsInEngine": true, "enabled": true, "overridden": false, "available": true, "disabledReason": null},
  {"code": "join", "name": "Join", "kind": "Process", "description": "Joins the rows with an earlier step's output on equal keys (inner or left).", "configSchema": {"type": "object", "properties": {"with": {"type": "string", "minLength": 1, "title": "Join with", "format": "step", "description": "The earlier step whose output is the right side."}, "on": {"type": "array", "items": {"type": "object", "properties": {"left": {"type": "string", "minLength": 1, "maxLength": 128, "title": "Left column", "format": "column"}, "right": {"type": "string", "minLength": 1, "maxLength": 128, "title": "Right column"}}, "additionalProperties": false, "required": ["left", "right"]}, "minItems": 1, "maxItems": 10, "title": "On"}, "type": {"type": "string", "enum": ["inner", "left"], "title": "Keep", "default": "inner", "description": "inner: matched rows only; left: every row of the input."}, "prefix": {"type": "string", "maxLength": 32, "title": "Prefix for clashing columns", "default": "right_"}}, "additionalProperties": false, "required": ["with", "on"]}, "backingService": "core", "retry": {"maxAttempts": 1, "delaySeconds": 0}, "timeoutSeconds": null, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": true, "runsInEngine": true, "enabled": true, "overridden": false, "available": true, "disabledReason": null},
  {"code": "read_api", "name": "Read API", "kind": "Read", "description": "Runs a saved API request (integration-service's runner) and takes its answer as rows.", "configSchema": {"type": "object", "properties": {"requestId": {"type": "integer", "minimum": 1, "title": "API request", "format": "api-request", "description": "A request saved in the workspace's API collections (integration-service)."}, "environmentId": {"type": "integer", "minimum": 1, "title": "Environment", "format": "api-environment", "description": "The environment whose variables the request runs with; none for the collection's default."}, "version": {"type": "integer", "minimum": 1, "title": "Collection version", "description": "Pin the request to a published collection version; empty for the request as it is now."}, "variables": {"type": "object", "additionalProperties": {"type": "string"}, "title": "Variables", "description": "Request variables by name; {{run}}, {{date}} and the other run placeholders are filled in."}, "rowsPath": {"type": "string", "maxLength": 255, "title": "Rows at", "description": "Where the rows are in the answer, as a dot path (data.items); empty for the pages' items, else the body."}, "maxRows": {"type": "integer", "minimum": 1, "maximum": 50000, "title": "At most rows", "description": "Stop after this many rows."}}, "additionalProperties": false, "required": ["requestId"]}, "backingService": "integration-service", "retry": {"maxAttempts": 3, "delaySeconds": 10}, "timeoutSeconds": 300, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": true, "runsInEngine": true, "enabled": false, "overridden": false, "available": false, "disabledReason": "integration-service's internal pipeline endpoints are not deployed yet (process.pipeline.integration.internal-endpoints is off)"},
  {"code": "read_database", "name": "Read Database", "kind": "Read", "description": "Runs a read-only query on a workspace database connection (integration-service) and takes its rows.", "configSchema": {"type": "object", "properties": {"connectionId": {"type": "integer", "minimum": 1, "title": "Connection", "format": "db-connection", "description": "One of the workspace's database connections."}, "query": {"type": "string", "minLength": 1, "maxLength": 20000, "title": "Query", "format": "sql", "description": "One read-only statement: SELECT, WITH, VALUES or TABLE."}, "maxRows": {"type": "integer", "minimum": 1, "maximum": 50000, "title": "At most rows", "description": "Stop after this many rows."}}, "additionalProperties": false, "required": ["connectionId", "query"]}, "backingService": "integration-service", "retry": {"maxAttempts": 2, "delaySeconds": 30}, "timeoutSeconds": 300, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": true, "runsInEngine": true, "enabled": false, "overridden": false, "available": false, "disabledReason": "integration-service's internal pipeline endpoints are not deployed yet (process.pipeline.integration.internal-endpoints is off)"},
  {"code": "read_file", "name": "Read CSV/JSON/Parquet", "kind": "Read", "description": "Reads one file of a workspace bucket — CSV, JSON, JSON Lines or Parquet — as rows (storage-service).", "configSchema": {"type": "object", "properties": {"bucket": {"type": "string", "minLength": 1, "maxLength": 255, "title": "Bucket", "format": "bucket", "description": "One of the workspace's own storage connections, by its alias. Empty, with the file empty too: the file the run was started for (inbox)."}, "key": {"type": "string", "minLength": 1, "maxLength": 1024, "title": "File", "format": "template", "description": "The object's key; {{date}} and the other run placeholders are filled in. Empty: the run's own file (inbox)."}, "format": {"type": "string", "enum": ["auto", "csv", "json", "jsonl", "parquet"], "title": "Format", "default": "auto", "description": "auto: by the key's extension."}, "delimiter": {"type": "string", "minLength": 1, "maxLength": 1, "title": "CSV delimiter", "default": ",", "description": "The character between a CSV's cells."}, "header": {"type": "boolean", "title": "CSV has a header row", "default": true, "description": "The first row names the columns; otherwise they are c1, c2, ..."}, "rowsPath": {"type": "string", "maxLength": 255, "title": "JSON rows at", "description": "Where the rows are in a JSON file, as a dot path (data.items); empty for the whole file."}, "maxRows": {"type": "integer", "minimum": 1, "maximum": 50000, "title": "At most rows", "description": "Stop after this many rows."}}, "additionalProperties": false}, "backingService": "storage-service", "retry": {"maxAttempts": 3, "delaySeconds": 10}, "timeoutSeconds": 600, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": true, "runsInEngine": true, "enabled": false, "overridden": false, "available": false, "disabledReason": "storage-service does not accept Core's pipeline caller (CORE_PIPELINES) yet (process.pipeline.storage.trusted-caller is off)"},
  {"code": "read_s3", "name": "Read S3", "kind": "Read", "description": "Lists the objects under a prefix of a workspace bucket, or reads all of them as rows (storage-service).", "configSchema": {"type": "object", "properties": {"bucket": {"type": "string", "minLength": 1, "maxLength": 255, "title": "Bucket", "format": "bucket", "description": "One of the workspace's own storage connections, by its alias."}, "prefix": {"type": "string", "maxLength": 1024, "title": "Prefix", "default": "", "description": "Only objects whose keys start with this; {{date}} and the other run placeholders are filled in."}, "format": {"type": "string", "enum": ["list", "auto", "csv", "json", "jsonl", "parquet"], "title": "Read as", "default": "list", "description": "list: one row per object. Otherwise each object's rows (auto: by its extension)."}, "limit": {"type": "integer", "minimum": 1, "maximum": 1000, "title": "At most objects", "default": 100}, "delimiter": {"type": "string", "minLength": 1, "maxLength": 1, "title": "CSV delimiter", "default": ",", "description": "The character between a CSV's cells."}, "header": {"type": "boolean", "title": "CSV has a header row", "default": true, "description": "The first row names the columns; otherwise they are c1, c2, ..."}, "rowsPath": {"type": "string", "maxLength": 255, "title": "JSON rows at", "description": "Where the rows are in a JSON file, as a dot path (data.items); empty for the whole file."}, "maxRows": {"type": "integer", "minimum": 1, "maximum": 50000, "title": "At most rows", "description": "Stop after this many rows."}}, "additionalProperties": false, "required": ["bucket"]}, "backingService": "storage-service", "retry": {"maxAttempts": 3, "delaySeconds": 10}, "timeoutSeconds": 600, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": true, "runsInEngine": true, "enabled": false, "overridden": false, "available": false, "disabledReason": "storage-service does not accept Core's pipeline caller (CORE_PIPELINES) yet (process.pipeline.storage.trusted-caller is off)"},
  {"code": "sample", "name": "Sample rows", "kind": "Read", "description": "Rows written in the step itself: a sample to build and test a pipeline on.", "configSchema": {"type": "object", "properties": {"rows": {"type": "array", "items": {"type": "object", "additionalProperties": {"type": ["string", "number", "boolean", "null"]}}, "maxItems": 1000, "title": "Rows", "description": "Each row an object of column: value (text, a number, true/false or null)."}}, "additionalProperties": false, "required": ["rows"]}, "backingService": "core", "retry": {"maxAttempts": 1, "delaySeconds": 0}, "timeoutSeconds": null, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": true, "runsInEngine": true, "enabled": true, "overridden": false, "available": true, "disabledReason": null},
  {"code": "save_file", "name": "Save File", "kind": "Output", "description": "Keeps the rows as a CSV, JSON or JSON Lines file with the run.", "configSchema": {"type": "object", "properties": {"fileName": {"type": "string", "pattern": "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$", "title": "File name", "description": "letters, digits, '.', '-' and '_', at most 128"}, "format": {"type": "string", "enum": ["csv", "json", "jsonl"], "title": "Format", "default": "csv"}}, "additionalProperties": false, "required": ["fileName"]}, "backingService": "core", "retry": {"maxAttempts": 1, "delaySeconds": 0}, "timeoutSeconds": null, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": true, "runsInEngine": true, "enabled": true, "overridden": false, "available": true, "disabledReason": null},
  {"code": "select", "name": "Select columns", "kind": "Process", "description": "Keeps the columns it names, in that order, optionally renamed.", "configSchema": {"type": "object", "properties": {"columns": {"type": ["array", "object"], "title": "Columns", "description": "A list of column names to keep, or an object {from: to} to keep and rename."}, "required": {"type": "boolean", "title": "Fail on a missing column", "default": false, "description": "Fail the step when the input has no such column; otherwise the column is empty."}}, "additionalProperties": false, "required": ["columns"]}, "backingService": "core", "retry": {"maxAttempts": 1, "delaySeconds": 0}, "timeoutSeconds": null, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": true, "runsInEngine": true, "enabled": true, "overridden": false, "available": true, "disabledReason": null},
  {"code": "send_notification", "name": "Send Notification", "kind": "Output", "description": "Sends a notice about the run to the job's owner, the workspace's admins, everyone, or named people.", "configSchema": {"type": "object", "properties": {"title": {"type": "string", "minLength": 1, "maxLength": 200, "title": "Title", "format": "template", "description": "{{rows}}, {{pipeline}}, {{run}}, {{date}} and the other run placeholders are filled in."}, "message": {"type": "string", "maxLength": 2000, "title": "Message", "format": "multiline"}, "severity": {"type": "string", "enum": ["INFO", "SUCCESS", "WARNING", "ERROR"], "title": "Severity", "default": "INFO"}, "to": {"type": "string", "enum": ["owner", "admins", "everyone", "users"], "title": "To", "default": "owner"}, "userIds": {"type": "array", "items": {"type": "integer", "minimum": 1}, "maxItems": 500, "title": "People", "format": "user", "description": "to: users — members of the workspace, by id."}, "when": {"type": "string", "enum": ["always", "has_rows", "no_rows"], "title": "Send", "default": "always"}, "link": {"type": "string", "pattern": "^/[^\\s]{0,254}$", "title": "Link", "default": "/jobList", "description": "A console path the notice opens, starting with /"}}, "additionalProperties": false, "required": ["title"]}, "backingService": "notifications-service", "retry": {"maxAttempts": 1, "delaySeconds": 0}, "timeoutSeconds": 120, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": true, "runsInEngine": true, "enabled": true, "overridden": false, "available": true, "disabledReason": null},
  {"code": "transform", "name": "Transform", "kind": "Process", "description": "Maps each row to new columns: copy, constant, concat, upper/lower/trim, cast, coalesce, replace.", "configSchema": {"type": "object", "properties": {"mappings": {"type": "array", "items": {"type": "object", "properties": {"target": {"type": "string", "minLength": 1, "maxLength": 128, "title": "Column", "description": "The column it makes."}, "op": {"type": "string", "enum": ["copy", "constant", "concat", "upper", "lower", "trim", "cast", "coalesce", "replace"], "title": "Operation", "default": "copy"}, "source": {"type": "string", "maxLength": 128, "title": "From column", "format": "column"}, "sources": {"type": "array", "items": {"type": "string", "maxLength": 128, "format": "column"}, "title": "From columns", "description": "concat and coalesce: the columns, in order."}, "value": {"type": ["string", "number", "boolean", "null"], "title": "Value", "description": "constant: the value; coalesce: the fallback."}, "separator": {"type": "string", "maxLength": 32, "title": "Separator", "default": "", "description": "concat: between values."}, "to": {"type": "string", "enum": ["text", "integer", "number", "boolean"], "title": "Cast to"}, "nullOnError": {"type": "boolean", "title": "Empty when it cannot cast", "default": false}, "search": {"type": "string", "minLength": 1, "maxLength": 256, "title": "Replace"}, "replacement": {"type": "string", "maxLength": 256, "title": "With", "default": ""}}, "additionalProperties": false, "required": ["target"]}, "minItems": 1, "maxItems": 200, "title": "Mappings"}, "keepUnmapped": {"type": "boolean", "title": "Keep the other columns", "default": false, "description": "Pass the input's columns on too; otherwise only the mapped ones."}}, "additionalProperties": false, "required": ["mappings"]}, "backingService": "core", "retry": {"maxAttempts": 1, "delaySeconds": 0}, "timeoutSeconds": null, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": true, "runsInEngine": true, "enabled": true, "overridden": false, "available": true, "disabledReason": null},
  {"code": "upload_bucket", "name": "Upload to bucket", "kind": "Output", "description": "Writes the rows as a CSV, JSON or JSON Lines object in a workspace bucket (storage-service).", "configSchema": {"type": "object", "properties": {"bucket": {"type": "string", "minLength": 1, "maxLength": 255, "title": "Bucket", "format": "bucket", "description": "One of the workspace's own storage connections, by its alias."}, "key": {"type": "string", "minLength": 1, "maxLength": 1024, "title": "Object key", "format": "template", "description": "Where to write it; {{run}}, {{date}}, {{time}}, {{pipeline}} and the other run placeholders are filled in."}, "format": {"type": "string", "enum": ["csv", "json", "jsonl"], "title": "Format", "default": "csv"}}, "additionalProperties": false, "required": ["bucket", "key"]}, "backingService": "storage-service", "retry": {"maxAttempts": 3, "delaySeconds": 10}, "timeoutSeconds": 600, "requiredPermission": "TENANT_ADMIN", "enabledByDefault": true, "overridable": true, "runsInEngine": true, "enabled": false, "overridden": false, "available": false, "disabledReason": "storage-service does not accept Core's pipeline caller (CORE_PIPELINES) yet (process.pipeline.storage.trusted-caller is off)"},
  {"code": "validate", "name": "Validate", "kind": "Process", "description": "Checks each row against a data contract (integration-service): fail, drop or flag the rows that do not hold.", "configSchema": {"type": "object", "properties": {"contractId": {"type": "integer", "minimum": 1, "title": "Contract", "format": "data-contract", "description": "One of the workspace's data contracts; or name a system contract below."}, "contractName": {"type": "string", "maxLength": 255, "title": "Contract name", "description": "A contract by name: the workspace's, else a system contract."}, "version": {"type": "integer", "minimum": 1, "title": "Contract version", "description": "A version to hold to; empty for the contract's active version."}, "onInvalid": {"type": "string", "enum": ["fail", "drop", "flag"], "title": "Rows that do not hold", "default": "fail", "description": "fail the step, drop the rows, or flag them (_valid, _errors) and go on."}}, "additionalProperties": false}, "backingService": "integration-service", "retry": {"maxAttempts": 2, "delaySeconds": 10}, "timeoutSeconds": 300, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": true, "runsInEngine": true, "enabled": false, "overridden": false, "available": false, "disabledReason": "integration-service's internal pipeline endpoints are not deployed yet (process.pipeline.integration.internal-endpoints is off)"},
  {"code": "write_database", "name": "Write Database", "kind": "Output", "description": "Inserts or upserts the rows into a table of a workspace database connection (integration-service). Off by default.", "configSchema": {"type": "object", "properties": {"connectionId": {"type": "integer", "minimum": 1, "title": "Connection", "format": "db-connection"}, "table": {"type": "string", "pattern": "^[A-Za-z_][A-Za-z0-9_]{0,62}(\\.[A-Za-z_][A-Za-z0-9_]{0,62})?$", "title": "Table", "description": "table or schema.table: letters, digits and '_'"}, "mode": {"type": "string", "enum": ["insert", "upsert"], "title": "Write as", "default": "insert"}, "keyColumns": {"type": "array", "items": {"type": "string", "pattern": "^[A-Za-z_][A-Za-z0-9_]{0,62}(\\.[A-Za-z_][A-Za-z0-9_]{0,62})?$", "format": "column"}, "maxItems": 10, "title": "Key columns", "description": "upsert: the columns a row is matched on."}, "columns": {"type": "array", "items": {"type": "string", "pattern": "^[A-Za-z_][A-Za-z0-9_]{0,62}(\\.[A-Za-z_][A-Za-z0-9_]{0,62})?$", "format": "column"}, "maxItems": 200, "title": "Columns", "description": "Only these columns; empty for all of the input's."}}, "additionalProperties": false, "required": ["connectionId", "table"]}, "backingService": "integration-service", "retry": {"maxAttempts": 1, "delaySeconds": 0}, "timeoutSeconds": 900, "requiredPermission": "TENANT_ADMIN", "enabledByDefault": false, "overridable": true, "runsInEngine": true, "enabled": false, "overridden": false, "available": false, "disabledReason": "integration-service has no database write path; MIG-229's connections are read-only (process.pipeline.integration.database-write is off)"},
  {"code": "legacy", "name": "Legacy: UI-CHECK step engine 0928", "kind": "Legacy", "description": "An existing pipeline, run by its worker exactly as before (the task's XML payload over Kafka).", "configSchema": {"type": "object", "properties": {"pipelineId": {"type": "string", "title": "Pipeline", "format": "pipeline", "description": "The existing pipeline (its pipelineId on the worker) this step is."}}, "additionalProperties": false}, "backingService": "worker", "retry": {"maxAttempts": 1, "delaySeconds": 0}, "timeoutSeconds": null, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": false, "runsInEngine": false, "enabled": true, "overridden": false, "available": true, "disabledReason": null, "pipelineKey": 100175, "pipelineId": "UI_CHECK_STEPS_0928", "config": {"pipelineId": "UI_CHECK_STEPS_0928"}},
  {"code": "legacy", "name": "Legacy: Reference: CSV check and summarise", "kind": "Legacy", "description": "An existing pipeline, run by its worker exactly as before (the task's XML payload over Kafka).", "configSchema": {"type": "object", "properties": {"pipelineId": {"type": "string", "title": "Pipeline", "format": "pipeline", "description": "The existing pipeline (its pipelineId on the worker) this step is."}}, "additionalProperties": false}, "backingService": "worker", "retry": {"maxAttempts": 1, "delaySeconds": 0}, "timeoutSeconds": null, "requiredPermission": "TENANT_USER", "enabledByDefault": true, "overridable": false, "runsInEngine": false, "enabled": true, "overridden": false, "available": true, "disabledReason": null, "pipelineKey": 100167, "pipelineId": "REF_CSV_CHECK_V1", "config": {"pipelineId": "REF_CSV_CHECK_V1"}},
] };

/** The schemas cut above, put back in their live shape: rows in (none for a Read task), rows out (none for Legacy). */
const ROWS = { type: 'array', items: { type: 'object', additionalProperties: { type: ['string', 'number', 'boolean', 'null'] } } };
const WITH_SCHEMAS = { ...REGISTRY_TASKS, data: REGISTRY_TASKS.data.map((t: any) => ({ ...t,
  inputSchema: t.kind === 'Read' ? null : { ...ROWS, description: 'Any rows.' },
  outputSchema: t.kind === 'Legacy' ? null : { ...ROWS, description: 'The rows it makes.' } })) };

const ANSWERS: Record<string, unknown> = { 'GET /pipeline.json/steps/tasks': WITH_SCHEMAS };

const clean = (text: string | null | undefined) => (text ?? '').replace(/\s+/g, ' ').trim();

/** Each row as a person reads it: its cells, in order. */
function rowsOf(v: Visit): string[] {
  return Array.from(v.main.querySelectorAll('tr[data-row]')).map(tr =>
    Array.from(tr.querySelectorAll('td')).map(td => clean(td.textContent)).filter(Boolean).join(' | '));
}

/** The open panel's settings and details, as a person reads them. */
function panelOf(): Record<string, unknown> {
  const panel = document.querySelector('.cdk-overlay-container app-task-panel') as HTMLElement | null;
  if (!panel) return { panel: null };
  return {
    ...detailsOf(panel),
    settings: Array.from(panel.querySelectorAll('[data-setting]')).map(s => s.getAttribute('data-setting')),
    state: clean(panel.querySelector('app-task-state')?.textContent),
    switchable: !!panel.querySelector('input[role="switch"]:not([disabled])'),
  };
}

describe('MIG-250: Configuration › Task Registry', () => {
  useMemoryStorage();
  afterEach(() => { restoreClock(); closeOverlays(); });

  it('the registry, as a workspace administrator', async () => {
    const v = await visit('/configuration/task-registry', 'TENANT_ADMIN', null, ANSWERS);
    pin(FILE, 'the registry, as a workspace administrator', { ...v.surface, rows: rowsOf(v) }, PINNED);
  });

  it('the registry, as a platform administrator', async () => {
    const v = await visit('/configuration/task-registry', 'PLATFORM_ADMIN', null, ANSWERS);
    pin(FILE, 'the registry, as a platform administrator', { ...v.surface, rows: rowsOf(v) }, PINNED);
  });

  it('the registry, as a tenant user (admin-only)', async () => {
    const v = await visit('/configuration/task-registry', 'TENANT_USER', TU_PAGES, ANSWERS);
    pin(FILE, 'the registry, as a tenant user (admin-only)', v.surface, PINNED);
  });

  it('the registry when Core cannot read it', async () => {
    const v = await visit('/configuration/task-registry', 'TENANT_ADMIN', null, {
      'GET /pipeline.json/steps/tasks': { status: 'ERROR', message: 'The Task Registry is not available.', data: null },
    });
    pin(FILE, 'the registry when Core cannot read it', { rows: rowsOf(v), alert: clean(v.main.querySelector('[role="alert"]')?.textContent) }, PINNED);
  });

  it('Legacy only', async () => {
    const v = await visit('/configuration/task-registry', 'TENANT_ADMIN', null, ANSWERS);
    const kind = v.main.querySelector('select[aria-label="Kind"]') as HTMLSelectElement;
    kind.value = 'Legacy';
    kind.dispatchEvent(new Event('change'));
    await v.settle();
    pin(FILE, 'Legacy only', { rows: rowsOf(v), options: Array.from(kind.options).map(o => clean(o.textContent)) }, PINNED);
  });

  it('a step task in the side panel, as a workspace administrator', async () => {
    const v = await visit('/configuration/task-registry', 'TENANT_ADMIN', null, ANSWERS);
    const requests = await click(v, 'Open Filter');
    pin(FILE, 'a step task in the side panel, as a workspace administrator', { requests, ...overlay(), ...panelOf() }, PINNED);
  });

  it('an unavailable task in the side panel', async () => {
    const v = await visit('/configuration/task-registry', 'TENANT_ADMIN', null, ANSWERS);
    await click(v, 'Open Write Database');
    pin(FILE, 'an unavailable task in the side panel', panelOf(), PINNED);
  });

  it('switching a task off from its panel', async () => {
    const v = await visit('/configuration/task-registry', 'TENANT_ADMIN', null, {
      ...ANSWERS,
      'POST /pipeline.json/steps/tasks/enabled': { status: 'SUCCESS', message: "'join' is switched off in this workspace.", data: {
        ...(WITH_SCHEMAS.data.find((t: any) => t.code === 'join') as object), enabled: false, overridden: true } },
    });
    await click(v, 'Open Join');
    const box = document.querySelector('.cdk-overlay-container input[role="switch"]') as HTMLInputElement;
    box.checked = false;
    box.dispatchEvent(new Event('change'));
    const requests = await v.settle();
    pin(FILE, 'switching a task off from its panel', { requests, ...panelOf(), buttons: overlay().buttons, row: rowsOf(v).find(r => r.includes('| join |') || r.startsWith('Join')) }, PINNED);
  });

  it('a Legacy row in the side panel', async () => {
    const v = await visit('/configuration/task-registry', 'TENANT_ADMIN', null, ANSWERS);
    const requests = await click(v, 'Open Reference: CSV check and summarise');
    pin(FILE, 'a Legacy row in the side panel', { requests, ...overlay(), ...panelOf() }, PINNED);
  });

  it('Edit pipeline from a Legacy row\'s panel opens the pipeline dialog', async () => {
    const v = await visit('/configuration/task-registry', 'TENANT_ADMIN', null, ANSWERS);
    await click(v, 'Open Reference: CSV check and summarise');
    const requests = await click(v, 'Edit pipeline');
    pin(FILE, 'Edit pipeline from a Legacy row\'s panel opens the pipeline dialog', { requests, ...overlay() }, PINNED);
  });
});
