import { Component, computed, effect, inject, input, output, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { DatePipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { API_BASE, API_SUCCESS, ApiResponse } from '../../../core/api/api.config';
import { ToastService } from '../../../shared/ui/toast.service';
import { DictationService } from '../../../shared/ui/dictation.service';
import { Icon } from '../../../shared/ui/icon';
import { StatusPill } from '../../../shared/ui/status-pill';
import { Donut } from '../../../shared/charts/donut';
import { RankedBar } from '../../../shared/charts/ranked-bar';
import { statusColor } from '../../../shared/charts/status-color';
import { parseTopicPartition } from '../../../shared/ui/topic';
import { classify, PRESETS, Intent } from './job-assistant.intents';
import {
  Answer, JobFacts, JobRun, answerFor, computeStats, humanDuration, runsToCsv,
} from './job-assistant.answers';

interface Turn {
  /** Monotonic, so two turns in the same millisecond cannot collide as @for track keys. */
  id: number;
  question: string;
  answer: Answer;
  at: Date;
}

/**
 * An assistant that knows one job and nothing else.
 *
 * Answers are composed from that job's own record and runs rather than generated by a model.
 * That is deliberate: the brief was that it must not wander into other jobs, and a scope rule
 * enforced in code cannot be talked out of it the way a prompt can. It also means every number
 * on screen is the real one, and the thing works without any AI provider configured.
 */
@Component({
  selector: 'app-job-assistant',
  imports: [Icon, DatePipe, RouterLink, StatusPill, Donut, RankedBar],
  templateUrl: './job-assistant.html',
  /*
   * In a panel the host has to be a flex item that can shrink, or the layout chain breaks
   * here. A component element is display:block with min-height:auto by default, so it sizes
   * to its content rather than to its parent: inside a 348px panel the host measured 4,733px,
   * which handed the transcript all the room it asked for and left nothing to scroll.
   */
  host: { '[class.assistant-fills-panel]': 'compact()' },
})
export class JobAssistant {
  readonly jobId = input.required<string>();
  /**
   * Panel mode. The same component, without the page chrome: no back link and no page title,
   * because a floating panel already says where it is and what it is about. Kept as one
   * component rather than two so the answers, exports and scope rules cannot drift apart.
   */
  readonly compact = input(false);
  readonly closed = output<void>();

  private readonly http = inject(HttpClient);
  private readonly toast = inject(ToastService);
  private readonly dictation = inject(DictationService);

  readonly voiceSupported = this.dictation.supported;
  /** Scoped per job so two open assistants cannot both claim the microphone. */
  private get micId(): string { return `assistant-${this.jobId()}`; }
  listening(): boolean { return this.dictation.listeningFor(this.micId); }

  /** Speech extends what is typed rather than replacing it. */
  toggleMic(): void {
    this.dictation.toggle(this.micId, said => {
      const current = this.question().trim();
      this.question.set(current ? `${current} ${said}` : said);
    });
  }

  readonly loading = signal(true);
  readonly error = signal('');
  readonly question = signal('');
  readonly turns = signal<Turn[]>([]);
  private turnId = 0;
  readonly exporting = signal<'csv' | 'xlsx' | null>(null);

  private loadTicket = 0;
  private readonly detail = signal<any | null>(null);
  readonly runs = signal<JobRun[]>([]);

  readonly presets = PRESETS;
  readonly outcomeColor = statusColor;

  /**
   * The configured AI agents, and the one this assistant will hand a question it cannot answer
   * from the job's own record.
   *
   * Until this existed the whole server-side assistant -- SourceJobRestApi.askAssistant, its
   * context builder, its scope prompt, its per-agent key resolution -- was unreachable: nothing
   * in the shipped bundle referenced it, so every question the seven local patterns missed got
   * "Try one of the buttons above" while a working model sat one unwired call away.
   */
  readonly agents = signal<{ aiAgentId: number; agentName: string }[]>([]);
  readonly agentId = signal<number | null>(null);
  readonly asking = signal(false);

  private loadAgents(): void {
    this.http.get<ApiResponse<{ aiAgentId: number; agentName: string }[]>>(
      `${API_BASE}/aiAgent.json/fetchAllAgents`).subscribe({
      // No agent configured is a normal state, not an error: the local answers below are the
      // product on their own, and the picker simply does not appear.
      next: response => {
        if (response.status !== API_SUCCESS) return;
        this.agents.set(response.data ?? []);
        if (this.agentId() === null && this.agents().length) {
          this.agentId.set(this.agents()[0].aiAgentId);
        }
      },
      error: () => { /* same: the assistant still answers everything it knows locally */ },
    });
  }

  readonly facts = computed<JobFacts | null>(() => {
    const job = this.detail();
    if (!job) return null;
    const task = job.taskDetail ?? {};
    return {
      jobId: job.jobId,
      jobName: job.jobName,
      jobStatus: job.jobStatus,
      execution: job.execution,
      priority: job.priority,
      lastJobRun: job.lastJobRun,
      assignedUsername: job.assignedUsername,
      taskName: task.taskName,
      taskType: task.sourceTaskType?.serviceName,
      topic: parseTopicPartition(task.sourceTaskType?.queueTopicPartition).topic || undefined,
      pipelineId: task.pipelineId,
      bucket: task.bucket,
      inputFolder: task.inputFolder,
      outputFolder: task.outputFolder,
      homePageId: task.homePageId,
      schedule: job.scheduler ?? null,
    };
  });

  readonly stats = computed(() => computeStats(this.runs()));

  /** Outcome mix for the donut, in the same colours the rest of the app uses for a status. */
  readonly outcomeMix = computed(() =>
    Object.entries(this.stats().byStatus)
      .map(([name, value]) => ({ name, value }))
      .sort((a, b) => b.value - a.value));

  /** The slowest runs, which is the shape of "why is this job slow". */
  readonly slowestRuns = computed(() =>
    this.runs()
      .filter(r => r.startTime && r.endTime)
      .map(r => ({
        name: `#${r.jobQueueId}`,
        value: Math.round(((new Date(r.endTime!).getTime() - new Date(r.startTime!).getTime()) / 1000) * 10) / 10,
      }))
      .sort((a, b) => b.value - a.value)
      .slice(0, 6)
      .map(row => ({ ...row, display: humanDuration(row.value) })));

  readonly humanDuration = humanDuration;

  constructor() {
    /*
     * Reload whenever the job changes, not only on first construction.
     *
     * As a page this component was built fresh per route, so ngOnInit was enough. In the panel
     * the instance is reused and only the input changes, and it went on showing the job it
     * happened to load first -- the header naming one job while the answers described another.
     */
    effect(() => {
      this.jobId();
      // Answers are about one job; carrying them across would put job A's run counts under
      // job B's name, which is precisely the confusion the scope rules exist to prevent.
      this.turns.set([]);
      this.question.set('');
      this.runs.set([]);
      this.load();
      if (!this.agents().length) this.loadAgents();
    });
  }

  load(): void {
    this.loading.set(true);
    this.error.set('');
    const jobId = this.jobId();
    // Switching jobs quickly leaves the earlier request in flight; only the newest may land.
    const ticket = ++this.loadTicket;

    this.http.get<ApiResponse<any>>(`${API_BASE}/sourceJob.json/fetchSourceJobDetailWithSourceJobId`,
      { params: { jobId } }).subscribe({
      next: response => {
        if (ticket !== this.loadTicket) return;
        if (response.status === API_SUCCESS) this.detail.set(response.data ?? null);
        else this.error.set(response.message);
        this.loading.set(false);
      },
      error: err => {
        if (ticket !== this.loadTicket) return;
        this.loading.set(false);
        this.error.set(err?.error?.message || 'Could not read this job.');
      },
    });

    this.http.get<ApiResponse<any>>(`${API_BASE}/sourceJob.json/fetchSourceJobQueueListWithJobId`,
      { params: { jobId } }).subscribe({
      next: response => {
        if (ticket !== this.loadTicket) return;
        if (response.status === API_SUCCESS) this.runs.set(response.data?.jobQueues ?? []);
      },
      error: () => { /* the assistant still answers what it can without run history */ },
    });
  }

  ask(text: string): void {
    const facts = this.facts();
    const asked = (text ?? '').trim();
    if (!asked || !facts) return;

    const scoped = classify(asked, facts.jobId);
    this.question.set('');

    /*
     * The local answer wins whenever it has one, and the agent only gets what falls through.
     *
     * That order is the point. A question the patterns match is answered from the job's own
     * record -- exact numbers, no provider needed, nothing a model could get wrong -- and only
     * 'unknown' means the assistant genuinely had nothing to say. 'out-of-scope' is NOT handed
     * over either: the rule that this assistant discusses one job is enforced in code here, and
     * delegating it to a prompt would make it something a question could talk its way past.
     */
    if (scoped.intent !== 'unknown' || !this.agentId()) {
      const answer = answerFor(scoped.intent, facts, this.runs(), scoped.mentionedJobId);
      this.turns.update(list =>
        [{ id: ++this.turnId, question: asked, answer, at: new Date() }, ...list]);
      return;
    }
    this.askAgent(asked, facts.jobId);
  }

  /**
   * Hands one question to the configured agent. The job's facts are NOT sent: the server
   * gathers them from the id itself, so a caller cannot pass off another job's data as context.
   */
  private askAgent(asked: string, jobId: number): void {
    const turn = ++this.turnId;
    const agent = this.agents().find(a => a.aiAgentId === this.agentId());
    const agentName = agent?.agentName ?? 'the agent';
    this.turns.update(list => [{
      id: turn, question: asked, at: new Date(),
      answer: { pending: true, blocks: [{ kind: 'ai', text: '', agent: agentName }] },
    }, ...list]);
    this.asking.set(true);

    const settle = (blocks: Answer['blocks'], refused = false) =>
      this.turns.update(list => list.map(t =>
        t.id === turn ? { ...t, answer: { blocks, refused } } : t));

    this.http.post<ApiResponse<string>>(`${API_BASE}/sourceJob.json/askAssistant`, {
      jobId, aiAgentId: this.agentId(), message: asked, history: this.history(),
    }).subscribe({
      next: response => {
        this.asking.set(false);
        // A business failure arrives as HTTP 200 with status ERROR, so the body decides.
        if (response.status !== API_SUCCESS || !response.data) {
          settle([{ kind: 'text', text: response.message || 'The agent did not reply.' }], true);
          return;
        }
        settle([{ kind: 'ai', text: String(response.data), agent: agentName }]);
      },
      error: err => {
        this.asking.set(false);
        settle([{ kind: 'text', text: err?.error?.message || 'The agent could not be reached.' }], true);
      },
    });
  }

  /**
   * The last few turns as plain alternating lines, oldest first -- `turns` is newest-first for
   * rendering, so it is reversed here. Capped because the whole thing rides in one prompt.
   */
  private history(): string[] {
    return this.turns()
      .filter(t => !t.answer.pending)
      .slice(0, 6)
      .reverse()
      .flatMap(t => [
        `User: ${t.question}`,
        `Assistant: ${t.answer.blocks
          .map(b => (b.kind === 'text' || b.kind === 'ai') ? b.text : '')
          .filter(Boolean).join(' ')}`,
      ])
      .filter(line => !line.endsWith(': '));
  }

  askPreset(intent: Intent, question: string): void {
    const facts = this.facts();
    if (!facts) return;
    const answer = answerFor(intent, facts, this.runs());
    this.turns.update(list => [{ id: ++this.turnId, question, answer, at: new Date() }, ...list]);
  }

  clear(): void { this.turns.set([]); }

  // ---- export ------------------------------------------------------------------------------

  /**
   * CSV is built here; XLSX is that CSV converted by the same LibreOffice path the document
   * converter uses, so there is no spreadsheet library in the browser.
   */
  exportRuns(format: 'csv' | 'xlsx'): void {
    const facts = this.facts();
    const runs = this.runs();
    if (!facts || !runs.length) {
      this.toast.info('There are no runs to export yet.');
      return;
    }

    const csv = runsToCsv(facts, runs);
    const base = `job-${facts.jobId}-runs`;

    if (format === 'csv') {
      this.save(new Blob([csv], { type: 'text/csv' }), `${base}.csv`);
      this.toast.success(`${runs.length} runs exported.`);
      return;
    }

    this.exporting.set('xlsx');
    this.http.post<ApiResponse<string>>(`${API_BASE}/fileChat.json/exportFile`, {
      content: csv, sourceFormat: 'csv', targetFormat: 'xlsx',
    }).subscribe({
      next: response => {
        this.exporting.set(null);
        if (response.status !== API_SUCCESS || !response.data) {
          this.toast.error(response.message || 'The spreadsheet could not be built.');
          return;
        }
        const bytes = Uint8Array.from(atob(response.data), c => c.charCodeAt(0));
        this.save(new Blob([bytes], {
          type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        }), `${base}.xlsx`);
        this.toast.success(`${runs.length} runs exported.`);
      },
      error: err => {
        this.exporting.set(null);
        this.toast.error(err?.error?.message || 'The spreadsheet could not be built.');
      },
    });
  }

  private save(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  }
}
