import { Component, OnInit, computed, inject, input, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { DatePipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { API_BASE, API_SUCCESS, ApiResponse } from '../../../core/api/api.config';
import { ToastService } from '../../../shared/ui/toast.service';
import { Icon } from '../../../shared/ui/icon';
import { StatusPill } from '../../../shared/ui/status-pill';
import { Donut } from '../../../shared/charts/donut';
import { RankedBar } from '../../../shared/charts/ranked-bar';
import { statusColor } from '../../../shared/charts/status-color';
import { parseTopicPartition } from '../../../shared/ui/topic';
import { classify, PRESETS, Intent } from './job-assistant.intents';
import {
  Answer, JobFacts, JobRun, answerFor, computeStats, humanDuration, runsToCsv,
} from './job-assistant.answers';

interface Turn {
  /** Monotonic, so two turns in the same millisecond cannot collide as @for track keys. */
  id: number;
  question: string;
  answer: Answer;
  at: Date;
}

/**
 * An assistant that knows one job and nothing else.
 *
 * Answers are composed from that job's own record and runs rather than generated by a model.
 * That is deliberate: the brief was that it must not wander into other jobs, and a scope rule
 * enforced in code cannot be talked out of it the way a prompt can. It also means every number
 * on screen is the real one, and the thing works without any AI provider configured.
 */
@Component({
  selector: 'app-job-assistant',
  imports: [Icon, DatePipe, RouterLink, StatusPill, Donut, RankedBar],
  templateUrl: './job-assistant.html',
})
export class JobAssistant implements OnInit {
  readonly jobId = input.required<string>();

  private readonly http = inject(HttpClient);
  private readonly toast = inject(ToastService);

  readonly loading = signal(true);
  readonly error = signal('');
  readonly question = signal('');
  readonly turns = signal<Turn[]>([]);
  private turnId = 0;
  readonly exporting = signal<'csv' | 'xlsx' | null>(null);

  private readonly detail = signal<any | null>(null);
  readonly runs = signal<JobRun[]>([]);

  readonly presets = PRESETS;
  readonly outcomeColor = statusColor;

  readonly facts = computed<JobFacts | null>(() => {
    const job = this.detail();
    if (!job) return null;
    const task = job.taskDetail ?? {};
    return {
      jobId: job.jobId,
      jobName: job.jobName,
      jobStatus: job.jobStatus,
      execution: job.execution,
      priority: job.priority,
      lastJobRun: job.lastJobRun,
      assignedUsername: job.assignedUsername,
      taskName: task.taskName,
      taskType: task.sourceTaskType?.serviceName,
      topic: parseTopicPartition(task.sourceTaskType?.queueTopicPartition).topic || undefined,
      pipelineId: task.pipelineId,
      bucket: task.bucket,
      inputFolder: task.inputFolder,
      outputFolder: task.outputFolder,
      homePageId: task.homePageId,
      schedule: job.scheduler ?? null,
    };
  });

  readonly stats = computed(() => computeStats(this.runs()));

  /** Outcome mix for the donut, in the same colours the rest of the app uses for a status. */
  readonly outcomeMix = computed(() =>
    Object.entries(this.stats().byStatus)
      .map(([name, value]) => ({ name, value }))
      .sort((a, b) => b.value - a.value));

  /** The slowest runs, which is the shape of "why is this job slow". */
  readonly slowestRuns = computed(() =>
    this.runs()
      .filter(r => r.startTime && r.endTime)
      .map(r => ({
        name: `#${r.jobQueueId}`,
        value: Math.round(((new Date(r.endTime!).getTime() - new Date(r.startTime!).getTime()) / 1000) * 10) / 10,
      }))
      .sort((a, b) => b.value - a.value)
      .slice(0, 6)
      .map(row => ({ ...row, display: humanDuration(row.value) })));

  readonly humanDuration = humanDuration;

  ngOnInit(): void { this.load(); }

  load(): void {
    this.loading.set(true);
    this.error.set('');
    const jobId = this.jobId();

    this.http.get<ApiResponse<any>>(`${API_BASE}/sourceJob.json/fetchSourceJobDetailWithSourceJobId`,
      { params: { jobId } }).subscribe({
      next: response => {
        if (response.status === API_SUCCESS) this.detail.set(response.data ?? null);
        else this.error.set(response.message);
        this.loading.set(false);
      },
      error: err => {
        this.loading.set(false);
        this.error.set(err?.error?.message || 'Could not read this job.');
      },
    });

    this.http.get<ApiResponse<any>>(`${API_BASE}/sourceJob.json/fetchSourceJobQueueListWithJobId`,
      { params: { jobId } }).subscribe({
      next: response => {
        if (response.status === API_SUCCESS) this.runs.set(response.data?.jobQueues ?? []);
      },
      error: () => { /* the assistant still answers what it can without run history */ },
    });
  }

  ask(text: string): void {
    const facts = this.facts();
    const asked = (text ?? '').trim();
    if (!asked || !facts) return;

    const scoped = classify(asked, facts.jobId);
    const answer = answerFor(scoped.intent, facts, this.runs(), scoped.mentionedJobId);
    this.turns.update(list => [{ id: ++this.turnId, question: asked, answer, at: new Date() }, ...list]);
    this.question.set('');
  }

  askPreset(intent: Intent, question: string): void {
    const facts = this.facts();
    if (!facts) return;
    const answer = answerFor(intent, facts, this.runs());
    this.turns.update(list => [{ id: ++this.turnId, question, answer, at: new Date() }, ...list]);
  }

  clear(): void { this.turns.set([]); }

  // ---- export ------------------------------------------------------------------------------

  /**
   * CSV is built here; XLSX is that CSV converted by the same LibreOffice path the document
   * converter uses, so there is no spreadsheet library in the browser.
   */
  exportRuns(format: 'csv' | 'xlsx'): void {
    const facts = this.facts();
    const runs = this.runs();
    if (!facts || !runs.length) {
      this.toast.info('There are no runs to export yet.');
      return;
    }

    const csv = runsToCsv(facts, runs);
    const base = `job-${facts.jobId}-runs`;

    if (format === 'csv') {
      this.save(new Blob([csv], { type: 'text/csv' }), `${base}.csv`);
      this.toast.success(`${runs.length} runs exported.`);
      return;
    }

    this.exporting.set('xlsx');
    this.http.post<ApiResponse<string>>(`${API_BASE}/fileChat.json/exportFile`, {
      content: csv, sourceFormat: 'csv', targetFormat: 'xlsx',
    }).subscribe({
      next: response => {
        this.exporting.set(null);
        if (response.status !== API_SUCCESS || !response.data) {
          this.toast.error(response.message || 'The spreadsheet could not be built.');
          return;
        }
        const bytes = Uint8Array.from(atob(response.data), c => c.charCodeAt(0));
        this.save(new Blob([bytes], {
          type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        }), `${base}.xlsx`);
        this.toast.success(`${runs.length} runs exported.`);
      },
      error: err => {
        this.exporting.set(null);
        this.toast.error(err?.error?.message || 'The spreadsheet could not be built.');
      },
    });
  }

  private save(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  }
}
