// Recorded by scripts/characterisation/record.mjs -- see ../harness.ts. Review the diff: it is the baseline.
export const PINNED: Record<string, unknown> = {
  "the menu for a platform administrator": [
    "Dashboard -> /dashboard",
    "Integration › Connector Hub — Databases, SaaS apps and files, ready to connect -> /integration/connectors",
    "Integration › API Collections — Which APIs exist, tested and versioned -> /integration/api-collections",
    "Integration › Sources — APIs, files and databases a pipeline reads -> /integration/sources",
    "Integration › Storage Connections — S3, Azure, MinIO, FTP -> /integration/storage-connections",
    "Pipelines › Pipelines — What a run does, and where -> /pipelines",
    "Pipelines › Schedules — When each pipeline runs, and its runs -> /pipelines/schedules",
    "Pipelines › Executions — Recent runs, and what waits for review -> /pipelines/executions",
    "Pipelines › Queue — What is in flight right now -> /pipelines/queue",
    "Pipelines › Run analytics — Group and measure your runs -> /pipelines/run-analytics",
    "Documents › Document Intelligence — Read documents into structured data -> /documents/intelligence",
    "Documents › Review queue — Check low-confidence fields -> /documents/review",
    "Documents › Document Converter — Convert between formats -> /documents/converter",
    "Documents › Reports — Documents made from your data -> /documents/reports",
    "Documents › Browse files — Upload, preview and share objects -> /documents/files",
    "Documents › Inbox — Upload files that start jobs -> /documents/inbox",
    "Documents › Audio Transcript — Speech to text -> /documents/transcript",
    "Data › Ask your data — Questions in plain language, with sources -> /data/ask",
    "Data › Data Catalog — Every dataset, owner, schema and sensitive field -> /data/catalog",
    "Data › Analytics Studio — Read a file as data, where it lives -> /data/analytics",
    "Data › Saved Analyses — Analyses and queries you kept, re-run on open -> /data/analytics/dashboards",
    "Forms › All forms — Fill in your workspace's forms; admins build them -> /forms/builder",
    "Forms › Submissions — Everything collected, and the runs it started -> /forms/submissions",
    "Workflows › Task inbox — Approvals and tasks waiting for you or your groups -> /workflows/inbox",
    "Workflows › Workflow designer — Who approves what, and what runs after -> /workflows/designer",
    "AI › AI Assistant — Ask in plain language, get runs and reports -> /ai/assistant",
    "AI › Tool Registry — What the assistant is allowed to call -> /ai/tools",
    "AI › Prompts — What a step says to a model -> /ai/prompts",
    "AI › Model connections — Providers, keys and caps -> /ai/connections",
    "Configuration › Task Registry — Every task a step can run, and each existing pipeline -> /configuration/task-registry",
    "Configuration › Kafka & Topics — Brokers, credentials and the topics that publish through them -> /configuration/kafka",
    "Configuration › Configuration values — Values and secrets a task reads as ${config:KEY} and ${secret:KEY} -> /configuration/values",
    "Configuration › Home pages — The addresses a task can name as its home page -> /configuration/home-pages",
    "Configuration › Task groups — Labels that group tasks together -> /configuration/task-groups",
    "Configuration › Engine settings — The scheduler fetch limit and the crons' watermarks -> /configuration/engine",
    "Billing › Cost & usage — What the workspace used this month and what it costs, line by line -> /billing/usage",
    "Billing › Invoices — Every month closed into a bill: status, balance, payment slips, receipts -> /billing/invoices",
    "Billing › Billing documents — Invoices, receipts, credit notes, statements and slips in one list -> /billing/documents",
    "Billing › Billing analytics — Invoiced, collected, overdue and churn across every workspace -> /billing/analytics",
    "Billing › Rate cards — The calculation behind every bill, versioned; a workspace can have its own -> /billing/rates",
    "Administration › Users — Who can sign in, and as what -> /administration/users",
    "Administration › Access profiles — Which pages your tenant users can open. -> /administration/access-profiles",
    "Administration › Data policies — Which models see each level of data, and for how long -> /administration/data-policies",
    "Administration › Tenants — Isolated workspaces -> /administration/tenants",
    "Administration › Workspace requests — Asks from outside for a workspace -> /administration/tenant-requests",
    "Administration › Managed service — Which of our staff may work in which workspace -> /administration/managed-service",
    "Administration › Staff activity — Every change our staff made in a customer's workspace -> /administration/staff-activity",
    "Administration › Work in a workspace — Open a managed session where you hold a grant -> /administration/work-in-workspace",
    "Administration › Reliability — Pipeline execution and billing against their 99.99% targets -> /administration/reliability"
  ],
  "the menu for a tenant user with every page": [
    "Dashboard -> /dashboard",
    "Integration › API Collections — Which APIs exist, tested and versioned -> /integration/api-collections",
    "Integration › Sources — APIs, files and databases a pipeline reads -> /integration/sources",
    "Pipelines › Pipelines — What a run does, and where -> /pipelines",
    "Pipelines › Schedules — When each pipeline runs, and its runs -> /pipelines/schedules",
    "Pipelines › Executions — Recent runs, and what waits for review -> /pipelines/executions",
    "Pipelines › Queue — What is in flight right now -> /pipelines/queue",
    "Pipelines › Run analytics — Group and measure your runs -> /pipelines/run-analytics",
    "Documents › Document Converter — Convert between formats -> /documents/converter",
    "Documents › Reports — Documents made from your data -> /documents/reports",
    "Documents › Browse files — Upload, preview and share objects -> /documents/files",
    "Documents › Inbox — Upload files that start jobs -> /documents/inbox",
    "Documents › Audio Transcript — Speech to text -> /documents/transcript",
    "Data › Analytics Studio — Read a file as data, where it lives -> /data/analytics",
    "Data › Saved Analyses — Analyses and queries you kept, re-run on open -> /data/analytics/dashboards",
    "AI › AI Assistant — Ask in plain language, get runs and reports -> /ai/assistant",
    "AI › Tool Registry — What the assistant is allowed to call -> /ai/tools",
    "AI › Prompts — What a step says to a model -> /ai/prompts"
  ],
  "the menu for a tenant user with five pages (api-check TU)": [
    "Dashboard -> /dashboard",
    "Pipelines › Pipelines — What a run does, and where -> /pipelines",
    "Pipelines › Schedules — When each pipeline runs, and its runs -> /pipelines/schedules",
    "Pipelines › Executions — Recent runs, and what waits for review -> /pipelines/executions",
    "Pipelines › Queue — What is in flight right now -> /pipelines/queue",
    "Pipelines › Run analytics — Group and measure your runs -> /pipelines/run-analytics",
    "Documents › Browse files — Upload, preview and share objects -> /documents/files",
    "Documents › Inbox — Upload files that start jobs -> /documents/inbox"
  ],
  "the menu for a tenant user with no page": [
    "Dashboard -> /dashboard"
  ],
  "the menu for a workspace administrator": [
    "Dashboard -> /dashboard",
    "Integration › Connector Hub — Databases, SaaS apps and files, ready to connect -> /integration/connectors",
    "Integration › API Collections — Which APIs exist, tested and versioned -> /integration/api-collections",
    "Integration › Sources — APIs, files and databases a pipeline reads -> /integration/sources",
    "Integration › Storage Connections — S3, Azure, MinIO, FTP -> /integration/storage-connections",
    "Pipelines › Pipelines — What a run does, and where -> /pipelines",
    "Pipelines › Schedules — When each pipeline runs, and its runs -> /pipelines/schedules",
    "Pipelines › Executions — Recent runs, and what waits for review -> /pipelines/executions",
    "Pipelines › Queue — What is in flight right now -> /pipelines/queue",
    "Pipelines › Run analytics — Group and measure your runs -> /pipelines/run-analytics",
    "Documents › Document Intelligence — Read documents into structured data -> /documents/intelligence",
    "Documents › Review queue — Check low-confidence fields -> /documents/review",
    "Documents › Document Converter — Convert between formats -> /documents/converter",
    "Documents › Reports — Documents made from your data -> /documents/reports",
    "Documents › Browse files — Upload, preview and share objects -> /documents/files",
    "Documents › Inbox — Upload files that start jobs -> /documents/inbox",
    "Documents › Audio Transcript — Speech to text -> /documents/transcript",
    "Data › Ask your data — Questions in plain language, with sources -> /data/ask",
    "Data › Data Catalog — Every dataset, owner, schema and sensitive field -> /data/catalog",
    "Data › Analytics Studio — Read a file as data, where it lives -> /data/analytics",
    "Data › Saved Analyses — Analyses and queries you kept, re-run on open -> /data/analytics/dashboards",
    "Forms › All forms — Fill in your workspace's forms; admins build them -> /forms/builder",
    "Forms › Submissions — Everything collected, and the runs it started -> /forms/submissions",
    "Workflows › Task inbox — Approvals and tasks waiting for you or your groups -> /workflows/inbox",
    "Workflows › Workflow designer — Who approves what, and what runs after -> /workflows/designer",
    "AI › AI Assistant — Ask in plain language, get runs and reports -> /ai/assistant",
    "AI › Tool Registry — What the assistant is allowed to call -> /ai/tools",
    "AI › Prompts — What a step says to a model -> /ai/prompts",
    "AI › Model connections — Providers, keys and caps -> /ai/connections",
    "Configuration › Task Registry — Every task a step can run, and each existing pipeline -> /configuration/task-registry",
    "Configuration › Kafka & Topics — Brokers, credentials and the topics that publish through them -> /configuration/kafka",
    "Configuration › Configuration values — Values and secrets a task reads as ${config:KEY} and ${secret:KEY} -> /configuration/values",
    "Configuration › Home pages — The addresses a task can name as its home page -> /configuration/home-pages",
    "Configuration › Task groups — Labels that group tasks together -> /configuration/task-groups",
    "Billing › Cost & usage — What the workspace used this month and what it costs, line by line -> /billing/usage",
    "Billing › Invoices — Every month closed into a bill: status, balance, payment slips, receipts -> /billing/invoices",
    "Billing › Billing documents — Invoices, receipts, credit notes, statements and slips in one list -> /billing/documents",
    "Administration › Users — Who can sign in, and as what -> /administration/users",
    "Administration › Access profiles — Which pages your tenant users can open. -> /administration/access-profiles",
    "Administration › Data policies — Which models see each level of data, and for how long -> /administration/data-policies"
  ]
};
