// Recorded by scripts/characterisation/record.mjs -- see ../harness.ts. Review the diff: it is the baseline.
export const PINNED: Record<string, unknown> = {
  "the menu for a platform administrator": [
    "Dashboard -> /dashboard",
    "Integration › Connector Hub Soon — Databases, SaaS apps and files, ready to connect -> /integration/connectors",
    "Integration › API Collections — Which APIs exist, tested and versioned -> /integration/api-collections",
    "Integration › Storage Connections — S3, Azure, MinIO, FTP -> /integration/storage-connections",
    "Pipelines › Pipelines — What a run does, and where -> /pipelines",
    "Pipelines › Schedules — When each pipeline runs, and its runs -> /pipelines/schedules",
    "Pipelines › Queue — What is in flight right now -> /pipelines/queue",
    "Pipelines › Run analytics — Group and measure your runs -> /pipelines/run-analytics",
    "Documents › Document Intelligence Soon — Read documents into structured data -> /documents/intelligence",
    "Documents › Review queue Soon — Check low-confidence fields -> /documents/review",
    "Documents › Document Converter — Convert between formats -> /documents/converter",
    "Documents › Browse files — Upload, preview and share objects -> /documents/files",
    "Documents › Audio Transcript — Speech to text -> /documents/transcript",
    "Data › Ask your data Soon — Questions in plain language, with sources -> /data/ask",
    "Data › Data Catalog Soon — Every dataset, owner, schema and sensitive field -> /data/catalog",
    "Data › Analytics Studio — Read a file as data, where it lives -> /data/analytics",
    "Data › Saved Analyses — Analyses and queries you kept, re-run on open -> /data/analytics/dashboards",
    "Forms › Form builder Soon — Build forms and share them securely -> /forms/builder",
    "Forms › Submissions Soon — Everything collected, with its approval state -> /forms/submissions",
    "Workflows › Task inbox Soon — Approvals and tasks waiting for you -> /workflows/inbox",
    "Workflows › Workflow designer Soon — Who approves what, and when -> /workflows/designer",
    "AI › Prompts — What a step says to a model -> /ai/prompts",
    "AI › Model connections — Providers, keys and caps -> /ai/connections",
    "Configuration › Task Registry — Each task type, the topic it publishes on, and its form -> /configuration/task-registry",
    "Configuration › Kafka & Topics — Brokers, credentials and the topics that publish through them -> /configuration/kafka",
    "Configuration › Configuration values — Values and secrets a task reads as ${config:KEY} and ${secret:KEY} -> /configuration/values",
    "Configuration › Home pages — The addresses a task can name as its home page -> /configuration/home-pages",
    "Configuration › Task groups — Labels that group tasks together -> /configuration/task-groups",
    "Configuration › Engine settings — The scheduler fetch limit and the crons' watermarks -> /configuration/engine",
    "Billing › Cost & usage — What the workspace used this month and what it costs, line by line -> /billing/usage",
    "Billing › Invoices — Every month closed into a bill: status, balance, payment slips, receipts -> /billing/invoices",
    "Billing › Billing documents — Invoices, receipts, credit notes, statements and slips in one list -> /billing/documents",
    "Billing › Billing analytics — Invoiced, collected, overdue and churn across every workspace -> /billing/analytics",
    "Billing › Rate cards — The calculation behind every bill, versioned; a workspace can have its own -> /billing/rates",
    "Administration › Users — Who can sign in, and as what -> /administration/users",
    "Administration › Access profiles — Which pages your tenant users can open. -> /administration/access-profiles",
    "Administration › Tenants — Isolated workspaces -> /administration/tenants",
    "Administration › Workspace Requests — Asks from outside for a workspace -> /administration/tenant-requests"
  ],
  "the menu for a tenant user with every page": [
    "Dashboard -> /dashboard",
    "Integration › API Collections — Which APIs exist, tested and versioned -> /integration/api-collections",
    "Pipelines › Pipelines — What a run does, and where -> /pipelines",
    "Pipelines › Schedules — When each pipeline runs, and its runs -> /pipelines/schedules",
    "Pipelines › Queue — What is in flight right now -> /pipelines/queue",
    "Pipelines › Run analytics — Group and measure your runs -> /pipelines/run-analytics",
    "Documents › Document Converter — Convert between formats -> /documents/converter",
    "Documents › Browse files — Upload, preview and share objects -> /documents/files",
    "Documents › Audio Transcript — Speech to text -> /documents/transcript",
    "Data › Analytics Studio — Read a file as data, where it lives -> /data/analytics",
    "Data › Saved Analyses — Analyses and queries you kept, re-run on open -> /data/analytics/dashboards",
    "AI › Prompts — What a step says to a model -> /ai/prompts"
  ],
  "the menu for a tenant user with five pages (api-check TU)": [
    "Dashboard -> /dashboard",
    "Pipelines › Pipelines — What a run does, and where -> /pipelines",
    "Pipelines › Schedules — When each pipeline runs, and its runs -> /pipelines/schedules",
    "Pipelines › Queue — What is in flight right now -> /pipelines/queue",
    "Pipelines › Run analytics — Group and measure your runs -> /pipelines/run-analytics",
    "Documents › Browse files — Upload, preview and share objects -> /documents/files"
  ],
  "the menu for a tenant user with no page": [
    "Dashboard -> /dashboard"
  ],
  "the menu for a workspace administrator": [
    "Dashboard -> /dashboard",
    "Integration › Connector Hub Soon — Databases, SaaS apps and files, ready to connect -> /integration/connectors",
    "Integration › API Collections — Which APIs exist, tested and versioned -> /integration/api-collections",
    "Integration › Storage Connections — S3, Azure, MinIO, FTP -> /integration/storage-connections",
    "Pipelines › Pipelines — What a run does, and where -> /pipelines",
    "Pipelines › Schedules — When each pipeline runs, and its runs -> /pipelines/schedules",
    "Pipelines › Queue — What is in flight right now -> /pipelines/queue",
    "Pipelines › Run analytics — Group and measure your runs -> /pipelines/run-analytics",
    "Documents › Document Intelligence Soon — Read documents into structured data -> /documents/intelligence",
    "Documents › Review queue Soon — Check low-confidence fields -> /documents/review",
    "Documents › Document Converter — Convert between formats -> /documents/converter",
    "Documents › Browse files — Upload, preview and share objects -> /documents/files",
    "Documents › Audio Transcript — Speech to text -> /documents/transcript",
    "Data › Ask your data Soon — Questions in plain language, with sources -> /data/ask",
    "Data › Data Catalog Soon — Every dataset, owner, schema and sensitive field -> /data/catalog",
    "Data › Analytics Studio — Read a file as data, where it lives -> /data/analytics",
    "Data › Saved Analyses — Analyses and queries you kept, re-run on open -> /data/analytics/dashboards",
    "Forms › Form builder Soon — Build forms and share them securely -> /forms/builder",
    "Forms › Submissions Soon — Everything collected, with its approval state -> /forms/submissions",
    "Workflows › Task inbox Soon — Approvals and tasks waiting for you -> /workflows/inbox",
    "Workflows › Workflow designer Soon — Who approves what, and when -> /workflows/designer",
    "AI › Prompts — What a step says to a model -> /ai/prompts",
    "AI › Model connections — Providers, keys and caps -> /ai/connections",
    "Configuration › Task Registry — Each task type, the topic it publishes on, and its form -> /configuration/task-registry",
    "Configuration › Kafka & Topics — Brokers, credentials and the topics that publish through them -> /configuration/kafka",
    "Configuration › Configuration values — Values and secrets a task reads as ${config:KEY} and ${secret:KEY} -> /configuration/values",
    "Configuration › Home pages — The addresses a task can name as its home page -> /configuration/home-pages",
    "Configuration › Task groups — Labels that group tasks together -> /configuration/task-groups",
    "Billing › Cost & usage — What the workspace used this month and what it costs, line by line -> /billing/usage",
    "Billing › Invoices — Every month closed into a bill: status, balance, payment slips, receipts -> /billing/invoices",
    "Billing › Billing documents — Invoices, receipts, credit notes, statements and slips in one list -> /billing/documents",
    "Administration › Users — Who can sign in, and as what -> /administration/users",
    "Administration › Access profiles — Which pages your tenant users can open. -> /administration/access-profiles"
  ]
};
