// Recorded by scripts/characterisation/record.mjs -- see ../harness.ts. Review the diff: it is the baseline.
export const PINNED: Record<string, unknown> = {
  "the menu for a platform administrator": [
    "Dashboard -> /dashboard",
    "Operations › Source Jobs — Scheduled work and its runs -> /operations/jobs",
    "Operations › Source Tasks — What a job does, and where -> /operations/tasks",
    "Operations › Queue — What is in flight right now -> /operations/queue",
    "Operations › Reports — Group and measure your runs -> /operations/reports",
    "Object Browser › Browse files — Upload, preview and share objects -> /objects/files",
    "Object Browser › Analytics Studio — Read a file as data, where it lives -> /objects/analytics",
    "Object Browser › Saved Analyses — Analyses and queries you kept, re-run on open -> /objects/analytics/dashboards",
    "Tools › Document Converter — Convert between formats -> /tools/converter",
    "Tools › Audio Transcript — Speech to text -> /tools/transcript",
    "Assistants › Prompts — What a step says to a model -> /assistants/prompts",
    "Assistants › Model connections — Providers, keys and caps -> /assistants/connections",
    "Configuration › Kafka & Topics — Brokers, credentials and the topics that publish through them -> /configuration/kafka",
    "Configuration › Pipelines — Each pipeline, the topic it publishes on, and its form -> /configuration/pipelines",
    "Configuration › Configuration values — Values and secrets a task reads as ${config:KEY} and ${secret:KEY} -> /configuration/values",
    "Configuration › Home pages — The addresses a task can name as its home page -> /configuration/home-pages",
    "Configuration › Task groups — Labels that group tasks together -> /configuration/task-groups",
    "Configuration › Engine settings — The scheduler fetch limit and the crons' watermarks -> /configuration/engine",
    "Configuration › Storage Connections — S3, Azure, MinIO, FTP -> /configuration/storage-connections",
    "Billing › Cost & usage — What the workspace used this month and what it costs, line by line -> /billing/usage",
    "Billing › Invoices — Every month closed into a bill: status, balance, payment slips, receipts -> /billing/invoices",
    "Billing › Billing documents — Invoices, receipts, credit notes, statements and slips in one list -> /billing/documents",
    "Billing › Billing analytics — Invoiced, collected, overdue and churn across every workspace -> /billing/analytics",
    "Billing › Rate cards — The calculation behind every bill, versioned; a workspace can have its own -> /billing/rates",
    "Administration › Users — Who can sign in, and as what -> /administration/users",
    "Administration › Access profiles — Which pages your tenant users can open. -> /administration/access-profiles",
    "Administration › Tenants — Isolated workspaces -> /administration/tenants",
    "Administration › Workspace Requests — Asks from outside for a workspace -> /administration/tenant-requests"
  ],
  "the menu for a tenant user with every page": [
    "Dashboard -> /dashboard",
    "Operations › Source Jobs — Scheduled work and its runs -> /operations/jobs",
    "Operations › Source Tasks — What a job does, and where -> /operations/tasks",
    "Operations › Queue — What is in flight right now -> /operations/queue",
    "Operations › Reports — Group and measure your runs -> /operations/reports",
    "Object Browser › Browse files — Upload, preview and share objects -> /objects/files",
    "Object Browser › Analytics Studio — Read a file as data, where it lives -> /objects/analytics",
    "Object Browser › Saved Analyses — Analyses and queries you kept, re-run on open -> /objects/analytics/dashboards",
    "Tools › Document Converter — Convert between formats -> /tools/converter",
    "Tools › Audio Transcript — Speech to text -> /tools/transcript",
    "Assistants › Prompts — What a step says to a model -> /assistants/prompts"
  ],
  "the menu for a tenant user with five pages (api-check TU)": [
    "Dashboard -> /dashboard",
    "Operations › Source Jobs — Scheduled work and its runs -> /operations/jobs",
    "Operations › Source Tasks — What a job does, and where -> /operations/tasks",
    "Operations › Queue — What is in flight right now -> /operations/queue",
    "Operations › Reports — Group and measure your runs -> /operations/reports",
    "Object Browser › Browse files — Upload, preview and share objects -> /objects/files"
  ],
  "the menu for a tenant user with no page": [
    "Dashboard -> /dashboard"
  ],
  "the menu for a workspace administrator": [
    "Dashboard -> /dashboard",
    "Operations › Source Jobs — Scheduled work and its runs -> /operations/jobs",
    "Operations › Source Tasks — What a job does, and where -> /operations/tasks",
    "Operations › Queue — What is in flight right now -> /operations/queue",
    "Operations › Reports — Group and measure your runs -> /operations/reports",
    "Object Browser › Browse files — Upload, preview and share objects -> /objects/files",
    "Object Browser › Analytics Studio — Read a file as data, where it lives -> /objects/analytics",
    "Object Browser › Saved Analyses — Analyses and queries you kept, re-run on open -> /objects/analytics/dashboards",
    "Tools › Document Converter — Convert between formats -> /tools/converter",
    "Tools › Audio Transcript — Speech to text -> /tools/transcript",
    "Assistants › Prompts — What a step says to a model -> /assistants/prompts",
    "Assistants › Model connections — Providers, keys and caps -> /assistants/connections",
    "Configuration › Kafka & Topics — Brokers, credentials and the topics that publish through them -> /configuration/kafka",
    "Configuration › Pipelines — Each pipeline, the topic it publishes on, and its form -> /configuration/pipelines",
    "Configuration › Configuration values — Values and secrets a task reads as ${config:KEY} and ${secret:KEY} -> /configuration/values",
    "Configuration › Home pages — The addresses a task can name as its home page -> /configuration/home-pages",
    "Configuration › Task groups — Labels that group tasks together -> /configuration/task-groups",
    "Configuration › Storage Connections — S3, Azure, MinIO, FTP -> /configuration/storage-connections",
    "Billing › Cost & usage — What the workspace used this month and what it costs, line by line -> /billing/usage",
    "Billing › Invoices — Every month closed into a bill: status, balance, payment slips, receipts -> /billing/invoices",
    "Billing › Billing documents — Invoices, receipts, credit notes, statements and slips in one list -> /billing/documents",
    "Administration › Users — Who can sign in, and as what -> /administration/users",
    "Administration › Access profiles — Which pages your tenant users can open. -> /administration/access-profiles"
  ]
};
